Климовских Кирилл
kontur-csharper/tdd pull request #101
Opened 2020-10-30 18:34 UTC by Klim0o0

@DerArvend

2020-10-31 18:52 UTC, DerArvend requested changes

2020-10-31 18:52 UTC, DerArvend commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +    public class CircularCloudLayouter
Я бы вынес интерфейс `TagCloudLayouter` для того чтобы в коде, вызывающем алгоритм раскладки облака тэгов можно было зависеть от абстрактного алгоритма раскладки, а не только от Circular

2020-10-31 18:52 UTC, DerArvend commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        private List<Rectangle> rectangels= new List<Rectangle>();
Опечатка в `rectangles`

2020-10-31 18:52 UTC, DerArvend commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        //private List<Point> points;
Это убирай)

2020-10-31 18:52 UTC, DerArvend commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        private IEnumerable<Point> GetSpiralPoints()
А давай вынесем спираль в отдельный класс, а в конструкторе `CircularCloudLayouter` будем зависеть от интерфейса спирали, которую будет реализовывать этот класс. Тогда можно будет расширять поведение класса `CircularCloudLayouter` не меняя его код. Например, можно будет закинуть эллиптическую, квадратную или любую другую спираль

2020-10-31 18:52 UTC, DerArvend commented on cs/TagsCloudVisualizationTests/CircularCloudLayouter_shuld.cs
> +            (circleSquare / circleSquare).Should().BeLessThan(1.5);
Лучше вынести `1.5` в константу. Не то чтобы что-то от этого сильно поменяется, но если надо будет поменять разрешенное отклонение от идеального круга, то будет легче найти глазами где надо менять код

2020-11-01 16:47 UTC, Klim0o0 commented on cs/TagsCloudVisualization/TagsCloudVisualization.csproj
> +        <TargetFramework>net48</TargetFramework>
Просто я создал проект для отрисовки и на Framework, и он не хотел взаимодействовать с Core

2020-11-02 09:51 UTC, Klim0o0 commented on cs/tdd.sln
> +EndProject
А проект с визуализацией тоже нужно коммитить ?

2020-11-02 10:31 UTC, Klim0o0 commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +    public class CircularCloudLayouter
Сделал

2020-11-02 10:31 UTC, Klim0o0 commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        private List<Rectangle> rectangels= new List<Rectangle>();
сделал

2022-11-01 05:44 UTC, closed without merging