Елизавета Штоль
kontur-csharper/tdd pull request #108
Opened 2020-10-31 23:21 UTC by elizShtol

@kindarad

2020-11-01 09:18 UTC, elizShtol commented
@goodoldlameme

2020-11-01 15:29 UTC, goodoldlameme requested changes

2020-11-01 15:29 UTC, goodoldlameme commented on cs/TagsCloudVisualization/TestsForCircularCloudLayouter.cs
> +            rectangles[0].X.Should().Be(pictureWidth / 2);
было бы хорошо проверить, что нужное поведение сохраняется если всего один положить прямоугольник

2020-11-01 15:29 UTC, goodoldlameme commented on cs/TagsCloudVisualization/TestsForCircularCloudLayouter.cs
> +            for (int i = 0; i < 70; i++)
кажется, что во всех тестах можно заменить for на foreach или запомнить в какую-то константу сколько прямоугольников мы нагенерировали

2020-11-01 15:29 UTC, goodoldlameme commented on cs/TagsCloudVisualization/TestsForCircularCloudLayouter.cs
> +            var radius = Math.Max(Math.Max(GetDistanceBetweenPoints(center, rectangles[69].Location),
тяжело читать, как-то декомпозировать нужно

подумай как заменить получение 69 элемента и делать это более гибким способом, чтобы когда мы меняем тесты нам не приходилось везде эти 69 менять

2020-11-01 15:29 UTC, goodoldlameme commented on cs/TagsCloudVisualization/TestsForCircularCloudLayouter.cs
> +            (squareOfRectangles / (Math.PI * radius * radius)).Should().BeGreaterThan(0.25);
мы хотим, чтобы площадь обрамляющего круга и площадь, занимаемая прямоугольниками были примерно равны, соответственно отношение большего(площадь круга всегда больше будет) к меньшему должно быть примерно 1 равно, точно, конечно не получится, но сейчас еще можно подтюнить тест, чтобы это точнее проверялось

2020-11-01 15:29 UTC, goodoldlameme commented on cs/TagsCloudVisualization/Painter.cs
> +            if (rectangle.Left >= 30 && rectangle.Top >= 30 && rectangle.Right <= bitmap.Width - 30 &&
магические константы

2020-11-03 15:48 UTC, goodoldlameme requested changes

2020-11-03 15:48 UTC, goodoldlameme commented on cs/Tests/Tests.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
проект с тестами обычно называется как проект, который тестируют плюс слово tests

2020-11-03 15:48 UTC, goodoldlameme commented on cs/TagsCloudVisualization/TagsCloudVisualization.csproj
> +  <Import Project="..\packages\NUnit.3.12.0\build\NUnit.props" Condition="Exists('..\packages\NUnit.3.12.0\build\NUnit.props')" />
раз тесты унесли в другой проект, можно из этого все зависимости, относящиеся к тестам убрать

2020-11-03 15:48 UTC, goodoldlameme commented on cs/Tests/TestsForCircularCloudLayouter.cs
> +namespace TagsCloudVisualization
namespace обычно называется так же, как имя проекта + папка в которой лежит файл, если это не в корне проекта

2020-11-03 15:48 UTC, goodoldlameme commented on cs/Tests/TestsForCircularCloudLayouter.cs
> +            testContext = new TestContext(TestExecutionContext.CurrentContext);
В прошлом ревью писала, что Текущий TestConext не нужно создавать каждый раз, его можно из статического поля получать

2020-11-03 15:48 UTC, goodoldlameme commented on cs/Tests/TestsForCircularCloudLayouter.cs
> +        private double GetDistanceBetweenPoints(Point p1, Point p2)
в прошлом ревью писала, что это можно сделать методом-расширения

2020-11-03 15:48 UTC, goodoldlameme commented on cs/Tests/TestsForCircularCloudLayouter.cs
> +        private bool RectanglesAreCrossed(Rectangle rectangle1, Rectangle rectangle2)
1) в прошлом ревью писала, что тут нарушается принцип dont repeat yourself, 2) потом поняла, что этот метод вообще лишний, у класса Rectangle есть уже готовый метод, который проверяет, что этот прямоугольник не пересекается с данным другим

2020-11-03 15:48 UTC, goodoldlameme commented on cs/Tests/TestsForCircularCloudLayouter.cs
> +                GetDistanceBetweenPoints(center, new Point(rectangles[69].Left, rectangles[69].Bottom));
тут осталось это магическое 69

2020-11-03 15:48 UTC, goodoldlameme commented on cs/Tests/TestsForCircularCloudLayouter.cs
> +            var radius = Math.Max(
давай вынесем все действия, относящиеся к расчету радиуса в отдельный метод

2020-11-03 15:48 UTC, goodoldlameme commented on cs/Tests/TestsForCircularCloudLayouter.cs
> +            (squareOfRectangles / squareOfFramingCircle).Should().BeInRange(0.25, 1);
0.25 это как-то маловато, не кажется? то есть это всего 25 процентов из  площади "идеального круга" занимает площадь наших прямоугольников

2020-11-03 15:48 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            while (RectanglesAreCrossed(rectangle, lastRectangle))
все еще актуально

2020-11-03 15:48 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            {
все еще актуально

2020-11-03 15:48 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        private Tuple<int, int> GetCoordinatesOfRectangle(Size rectangleSize)
все еще актуально

2020-11-03 15:48 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            if (x >= center.X && y <= center.Y)
все еще актуально

2020-11-03 15:48 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        private double GetDiagonalOfRectangle(Rectangle rectangle)
все еще актуально

2020-11-03 15:48 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        private bool RectanglesAreCrossed(Rectangle rectangle1, Rectangle rectangle2)
как в тестах писала, этот метод вообще лишний, есть уже встроенный

2020-11-06 08:58 UTC, goodoldlameme commented on cs/TagsCloudVisualization/TagsCloudVisualization.csproj
> +  <Import Project="..\packages\NUnit.3.12.0\build\NUnit.props" Condition="Exists('..\packages\NUnit.3.12.0\build\NUnit.props')" />
все еще актуально

2020-11-06 09:55 UTC, goodoldlameme requested changes

2020-11-06 09:55 UTC, goodoldlameme commented on cs/TagsCloudVisualization/TagsCloudVisualization.csproj
> -    <Reference Include="FluentAssertions, Version=5.10.3.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a, processorArchitecture=MSIL">
в этом файле еще есть зависимости, относящиеся к тестам их бы тоже убрать(теги import в начале файла)

2020-11-06 09:55 UTC, goodoldlameme commented on cs/CircularCloudLayouterTests/CircularCloudLayouterTests.cs
>  {
можно еще добавить тест на то, что это действительно спираль, что следующая точка ложится примерно туда, куда ты ждешь

2020-11-06 09:55 UTC, goodoldlameme commented on cs/CircularCloudLayouterTests/CircularCloudLayouterTests.cs
>          {
github не дает мне поставить комментарий туда, куда нужно - строка 48 можно не заводить локальную переменную для лэйаутера

2020-11-06 09:55 UTC, goodoldlameme commented on cs/CircularCloudLayouterTests/CircularCloudLayouterTests.cs
> +            var center = rectangles[0].Location;
центр лучше сделать параметром метода

2020-11-06 09:55 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        private List<Rectangle> rectangles;
может быть readonly

2020-11-06 09:55 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
>                  anglePhi += deltaOfAnglePhi;
все, что касается изменения углов, поворотов, поворотов, шагов и получения следующей точки стоит инкапсулировать в отдельную сущность

2020-11-06 09:55 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            foreach (var rectangle1 in rectangles)
в таком случае лучше без цифр называт

2020-11-06 09:55 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            var x = pointOnSpiral.X + center.X;
я имела ввиду сдвиг который у тебя происходит в if-ах, а не сдвиг к центру, свдиг к центур это часть переводы в полярные координаты

2020-11-06 09:55 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
>              if (x >= center.X && y <= center.Y)
подумай как это упросить до двух if, без else

2020-11-06 09:55 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +namespace CircularCloudLayouterTests
что-то тут пошло не так

2020-11-06 09:55 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +namespace CircularCloudLayouterTests
есть такой тег для csproj файла rootnamespace, основываясь на него resharper тебе предлагает какой неймспейс сделать

2020-11-06 09:55 UTC, goodoldlameme commented on cs/TagsCloudVisualization/PointExtensions.cs
> +        public static double GetDistanceTo(this Point p1, Point p2)
на этот мтеод тоже нужно тесты написать

2020-11-06 09:55 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +namespace CircularCloudLayouterTests
относится ко всем файлам в этом проекте коммент

2020-11-06 17:50 UTC, goodoldlameme requested changes

2020-11-06 17:50 UTC, goodoldlameme commented on cs/CircularCloudLayouterTests/CircularCloudLayouterTests.cs
> +        public void RectanglesPlacedOnSpiral()
приведи нейминг тестов к одному стилю, плис, такому, который используется, к примеру в тесте на строке 47

2020-11-06 17:50 UTC, goodoldlameme commented on cs/CircularCloudLayouterTests/CircularCloudLayouterTests.cs
> +            var coefOfSpiral = this.circularCloudLayouter.Spiral.CoefOfSpiralEquation;
тут немного не то происходит, во-первых то, что поле со спиралью по сути должно быть приватным полем лейаутера, но ради теста его приходится выставлять наружу, во-вторых,  этот тест опирается на какую-то логику из этого класса спирали(увеличение угла), что делает его хрупким, 
я бы предложила посчитать просто руками посчитать ожидаемые расположения нескольких прямоугольников и сравнить, что алгоритм раскладывает их примерно так как нужно

2020-11-06 17:50 UTC, goodoldlameme commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
>          private List<Rectangle> rectangles;
может быть readonly

2020-11-06 17:50 UTC, goodoldlameme commented on cs/TagsCloudVisualization/Spiral.cs
> +    public class Spiral
на класс спирали тоже тесты нужны

2020-11-07 12:14 UTC, goodoldlameme approved these changes

2022-11-01 05:43 UTC, closed without merging