Михаил Медведев
kontur-csharper/tdd pull request #110
Opened 2020-11-01 09:53 UTC by MaiklM

Михаил Медведев
@Hyperbodya

2020-11-01 11:21 UTC, Belianin requested changes
И не забудь сделать тест на плотность облака

2020-11-01 11:21 UTC, Belianin commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        private Point GetCentreRectangle(Rectangle rectangle)
Можно сделать extension-методом к Rectangle

2020-11-01 11:21 UTC, Belianin commented on cs/TagsCloudVisualization/CircularCloudLayouterTest.cs
> +        public void Test_PuFirstRectangleInCenterCloudZeroZero(int width, int height)
Опечатка в слове Put

2020-11-01 11:21 UTC, Belianin commented on cs/TagsCloudVisualization/CircularCloudLayouterTest.cs
> +        public void Test_PutFirstRectangleInCenterCloud(int x, int y, int width, int height)
Тест можно объединить с предыдущим

2020-11-01 11:21 UTC, Belianin commented on cs/TagsCloudVisualization/CircularCloudLayouterTest.cs
> +            var r = new CircularCloudLayouter(new Point(x, y)).PutNextRectangle(new Size(width, height));
Зачем такая экономия на строчках? Сделай, чтобы структура теста была ААА

2020-11-01 11:21 UTC, Belianin commented on cs/TagsCloudVisualization/CircularCloudLayouterTest.cs
> +            var random = new Random();
Я же просил передавать в Random фиксированный сид

2020-11-01 11:21 UTC, Belianin commented on cs/TagsCloudVisualization/CircularCloudLayouterTest.cs
> +        public void Test_PutRectanglesInCircle()
Хотелось бы посмотреть на этот тест с разными параметрами

2020-11-01 11:33 UTC, MaiklM commented on cs/TagsCloudVisualization/CircularCloudLayouterTest.cs
> +        public void Test_PutFirstRectangleInCenterCloud(int x, int y, int width, int height)
разве при стиле TDD я могу переделывать предыдущие тесты?
объединять их, например

2020-11-01 11:34 UTC, Belianin commented on cs/TagsCloudVisualization/CircularCloudLayouterTest.cs
> +        public void Test_PutFirstRectangleInCenterCloud(int x, int y, int width, int height)
После того как ты их написал, да. TDD это инструмент, который должен облегчить разработку, а не религия

2020-11-01 11:36 UTC, MaiklM commented on cs/TagsCloudVisualization/GetPointer.cs
> +        private double dangle { get => Math.PI / (2 * radius); }
dangle все равно что dx
я могу переименовать, но смысл именно в приращении

2020-11-01 11:38 UTC, MaiklM commented on cs/TagsCloudVisualization/CircularCloudLayouterTest.cs
> +            var random = new Random();
разве значение по умолчанию не фиксировано?

2020-11-01 11:44 UTC, Belianin commented on cs/TagsCloudVisualization/CircularCloudLayouterTest.cs
> +            var random = new Random();
Нет, в .NET Framework начальное значение по умолчанию зависит от времени. В .NET Core значение начального значения по умолчанию создается статическим генератором случайных чисел потока.

2020-11-01 11:44 UTC, Belianin commented on cs/TagsCloudVisualization/GetPointer.cs
> +        private double dangle { get => Math.PI / (2 * radius); }
Нет, тогда можешь оставить

2020-11-01 11:45 UTC, MaiklM commented on cs/TagsCloudVisualization/CircularCloudLayouterTest.cs
> +        public void Test_PutRectanglesInCircle()
параметры - в смысле с другими size, или площадью?

2020-11-05 08:57 UTC, Belianin commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        internal int Left { get; private set; }
Почему `internal`?

2020-11-05 08:57 UTC, Belianin commented on cs/TagsCloudVisualization/PointGetter.cs
> +        private double Dangle => Math.PI / (2 * radius);
лучше бы `dAngle` :))

2020-11-05 09:06 UTC, Belianin commented on cs/TagsCloudVisualization/TagsCloudVisualization.cs
> +        public static void Visualizate(CircularCloudLayouter cloud, string path)
Не стоит передавать в метод сам `CircularCloudLayouter `, лучше передавать сразу необходимые параметры: центр, размер картинки и набор прямоугольников

2022-11-01 05:43 UTC, closed without merging