Бусыгин Никита
kontur-csharper/tdd pull request #116
Opened 2020-11-01 19:45 UTC by xsitin

@P572

2020-11-02 19:35 UTC, P572 requested changes

2020-11-02 19:35 UTC, P572 commented on cs/CircularCloud/ArchimedeanSpiral.cs
> +        public Point Center { get; private set; }
сеттер вообще не нужен

2020-11-02 19:35 UTC, P572 commented on cs/CircularCloud/ArchimedeanSpiral.cs
> +        protected Point Previous = new Point(Int32.MaxValue, Int32.MinValue);
Почему именно такое значение? Если нужно задать какое-то начальное состояние, более очевидным вариантом будет null

2020-11-02 19:35 UTC, P572 commented on cs/CircularCloud/ArchimedeanSpiral.cs
> +                var r = Distance * Fi;
Я понимаю что это математическая часть, но это не повод называть переменные одной буквой.

2020-11-02 19:35 UTC, P572 commented on cs/CircularCloudTests/ArchimedeanSpiralTests.cs
> +            var a = spiral.GetNextPoint();
Называть переменные одной буквой - плохая практика. A, b - это что?

2020-11-02 19:35 UTC, P572 commented on cs/CircularCloudTests/CircularCloudLayouterTests.cs
> +                    var point = rectangle.Location + size - new Size(cloud.Center);
Не очень понимаю что тут происходит. Может можно как-то читабельность улучшить?

2020-11-02 20:02 UTC, xsitin commented on cs/CircularCloud/CircularCloudLayouter.cs
> +        public CircularCloudLayouter(Point center) => Spiral = new ArchimedeanSpiral(center);
Один раз захотел написать в конструкторе просто координаты, а не передавать точку, посчитал, что так будет удобнее.

2020-11-03 05:51 UTC, xsitin commented on cs/CircularCloud/ArchimedeanSpiral.cs
> +        protected Point Previous = new Point(Int32.MaxValue, Int32.MinValue);
Point структура, а им вроде нельзя присвоить null, по крайней мере при выключенных nullable типах(имеется ввиду конфигурация проекта, выбирается не далеко от версии языка)

2020-11-05 20:04 UTC, P572 commented on cs/CircularCloudTests/CircularCloudLayouterTests.cs
> +            Bitmap map = new Bitmap(2000, 2000);
Функционал рисования хотелось бы видеть в отдельном классе - все-таки это отдельная ответственность

2020-11-06 07:22 UTC, xsitin commented on cs/CircularCloud/ArchimedeanSpiral.cs
> +        protected double Angel;
Да, очепятка:)

2020-11-07 12:36 UTC, P572 approved these changes

2022-07-01 14:01 UTC, closed without merging