Лунев Данил
kontur-csharper/tdd pull request #136
Opened 2021-11-05 15:01 UTC by DaGnYMilleR

@bannikovilea

2021-11-05 15:44 UTC, bannikovilea requested changes

2021-11-05 15:44 UTC, bannikovilea commented on cs/Homework/TagsCloud.Tests/CircularCloudLayouterTests.cs
> +        private CircularCloudLayouter layouter;
Тестируемый объект в теории тестирования принято называть sut - от System Under Test

2021-11-05 15:44 UTC, bannikovilea commented on cs/Homework/TagsCloud.Tests/CircularCloudLayouterTests.cs
> +            rectangles = PutRandomRectangles(count);
Где-то rectangles является локальной переменное, где-то глобальной. Предлагаю везде сделать её локальной

2021-11-05 15:44 UTC, bannikovilea commented on cs/Homework/TagsCloud.Tests/CircularCloudLayouterTests.cs
> +        public void Rectangles_Should_BeTightlySpaced(int count)
В предыдущих тестах название отражает тестируемый метод и строится по паттерну - Метод_Условие_ОжидаемыйРезультат. 
В данном тесте по названию не совсем понятно, что происходит. Предлагаю подумать на именованием

2021-11-05 15:44 UTC, bannikovilea commented on cs/Homework/TagsCloud.Tests/CircularCloudLayouterTests.cs
> +            const int maxWidth = 100;
Максимальные длина и ширина захардкожены тут, во-первых не очевидно искать размер тут, во-вторых если один из тестов потребует изменения высоты или ширины придётся искать, где это происходит и переписывать метод, можно подумать над вынесением их в параметры метода или в приватные поля класса

2021-11-05 15:44 UTC, bannikovilea commented on cs/Homework/TagsCloud.Visualization/CircularCloudLayouter.cs
> +            throw new Exception();
Было бы не плохо в эксепшене сообщить о том, что пошло не так

2021-11-05 15:44 UTC, bannikovilea commented on cs/Homework/TagsCloud.Visualization/Drawer/Drawer.cs
> +            var (widthWithOffset, heightWithOffset) = (width + 100, height + 100);
Почему добавляем 100, а не 200? 

Давай вынесем их в переменные или поля

2021-11-05 16:40 UTC, DaGnYMilleR commented on cs/Homework/TagsCloud.Tests/CircularCloudLayouterTests.cs
> +            rectangles = PutRandomRectangles(count);
rectangles вынесено в поле класса для того, чтобы можно было получить прямоугольники, когда тест не проходит и отрисовать их

2021-11-08 02:34 UTC, bannikovilea commented on cs/Homework/TagsCloud.Tests/CircularCloudLayouterTests.cs
> +            var index = workingDirectory.IndexOf("TagsCloud", StringComparison.Ordinal);
Если мы не найдем в пути TagsCloud, то у нас потом substring развалится из-за того, что ему сунули минус один. 
Такое может произойти если дллку с тестами скопировали после сборки в какую-то папку, а потом тестировочный агент последовательно эти дллки себя вжирает и гоняет тесты. 
Давай что-нибудь с этим сделаем?

2021-11-15 02:25 UTC, bannikovilea commented on cs/Homework/TagsCloud.Visualization/LayoutContainer/ILayoutContainer.cs
> +        (int, int) GetWidthAndHeight();
Не критично, для большой читаемости, если не хочется усложнять код структурой, можно использовать именованный Tupple `(int Width, int Height) GetWidthAndHeight()`

2021-11-15 02:30 UTC, bannikovilea commented on cs/Homework/TagsCloud.Tests/CircularCloudLayouterTests.cs
> +        public void InitLayouter()
По названию метода и аргументу понятно зачем он нужен) Но в принципе, можно назвать его `SetUp()`

2021-11-15 02:32 UTC, bannikovilea commented on cs/Homework/TagsCloud.Visualization/LayoutContainer/WordsContainerBuilder.cs
> +            FontFactory.FontFactory fontFactory)
Тут интерфейс фабрики не забыл?)

2021-11-16 02:45 UTC, bannikovilea commented
После ревью @DaGnYMilleR остались положительные впечатления:
- коммиты: четкие и понятные названия, части работы структурированы по коммитам
- задача выполнена с опережением сроков
- сделаны дополнительные задания
- правки по ревью вносились быстро
- вопросы по существу и по делу

Для развития предлагаю потрогать другие DI контейнеры, например StructureMap. И какой-нибудь другой фреймворк для тестирования, например Autofixture

2021-11-16 02:45 UTC, closed without merging