Тебайкин Максим
kontur-csharper/tdd pull request #137
Opened 2021-11-05 18:44 UTC by gODeaLoAple

@hariton27sy

2021-11-07 11:08 UTC, hariton27sy requested changes

2021-11-07 11:08 UTC, hariton27sy commented on cs/TagsCloudVisualization/CircularVectorsGenerator.cs
> +        public IEnumerable<Point> Generate()
Мне не нравится смешанная реализация перечесления и использования этого метода. Возможно лучше стоит выбрать одно из двух:
1. Сделать метод GetNextPoint(). В таком случае сам класс будет отвечать за перечисление
2. В месте вызова вызывать метод Generate() лишь один раз, и потом итерироваться уже по полученному объекту, т.е. получается что этот метод вернет тебе как бы коллекцию, которую ты и будешь перечислять.

Почему мне не нравится такая реализация:
1. вызывая метод Generate, который возвращает IEnumerable, я ожидаю что в этом IEnumerable будут содержаться все элементы без эффекта памяти.
2. Кроме того в таком случае такая реализация уязвима к многопоточному коду, да даже к однопоточному где метод Generate вызывается в разных местах. Так например ты можешь вызывать в двух местах Generate и перечисляя параллельно в них ты будешь пропускать какие-то элементы в каждом из перечислений.

Можем подробнее обсудить это в телеге

2021-11-07 11:08 UTC, hariton27sy commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            ShiftRectangleToCenter(rectangle);
А ты уверен что этот метод работает? Посмотри чем является Rectangle struct или class?

2021-11-07 11:08 UTC, hariton27sy commented on cs/TagsCloudVisualization/SquareCalculator.cs
> +﻿using System;
Функции используются как вспомогательные для тестов. Возможно стоит перенести в проект с тестами в таком случае. Иначе непонятно, есть проект с генератором облаков, в котором есть какие-то левые функции

2021-11-07 11:08 UTC, hariton27sy commented on cs/TagsCloudVisualization/DistantPointFinder.cs
> +﻿using System.Collections.Generic;
Аналогично SquareCalculator. Функции используются как вспомогательные для тестов

2021-11-07 11:08 UTC, hariton27sy commented on cs/TagsCloudVisualization/Extensions/PointExtensions.cs
> +﻿using System;
Тоже перенести в Tests

2021-11-07 11:08 UTC, hariton27sy commented on cs/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +﻿using System.Collections.Generic;
Перенести в Tests

2021-11-07 11:08 UTC, hariton27sy commented on cs/TagsCloudVisualization/DrawerSettings.cs
> +﻿using System;
Название для этого класса не очень подходящее. Все же под таким названием подразумевались бы настройки для самого Drawer'а. Для этого класса больше бы подошло CloudGenerator или что-то с похожим смыслом, так как здесь по сути происходит. Да  и на самом деле я не совсем понимаю смысла этого класса прослойки.

Давай подробнее обсудим в телеграмме, если нужно

2021-11-07 11:08 UTC, hariton27sy commented on cs/TagsCloudVisualization/TagsCloudDrawer.cs
> +#pragma warning disable CA1416
Давай добавим комментарий к этой директиве, иначе непонятно зачем воткнули здесь это

2021-11-07 11:08 UTC, hariton27sy commented on cs/TagsCloudVisualization/TagsCloudDrawer.cs
> +            graphics.FillRectangle(Brushes.Gray, 0, 0, bitmap.Width, bitmap.Height);
Захардкожен цвет. Давай передавать его в конструктор. В таком случае как раз помог класс с названием TagsCloudDrawerSettings со всеми конфигами drawer'a

2021-11-07 11:08 UTC, hariton27sy commented on cs/TagsCloudVisualization/Program.cs
> +        private static Rectangle[] GenerateRectangles(int count, CircularCloudLayouter layouter, Func<Size> sizeFactory)
Перенеси этот метод в текущий DrawerSettings. И вызывай уже внутри него при вызове Draw. Тогда генерация(можно назвать бизнес-логикой😄) уже будет проходить при вызове соответствующего метода, а не при инициализации.

2021-11-07 11:13 UTC, gODeaLoAple commented on cs/TagsCloudVisualization/SquareCalculator.cs
> +﻿using System;
А есть ли смысл перенести это не в Tests, а в отдельный проект, скажем, Utils?

2021-11-07 11:16 UTC, gODeaLoAple commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            ShiftRectangleToCenter(rectangle);
Ахах, действительно, я не сдвигаю ректангл) Исправлю

2021-11-10 12:13 UTC, hariton27sy commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            var dir = new Point(_center.X - center.X, _center.Y - center.Y);
dir и shift можно сократить 😄, но не принципиально

2021-11-10 12:13 UTC, hariton27sy commented on cs/TagsCloudVisualization/TagsCloudGenerator.cs
> +        private Rectangle[] GenerateRectangles()
На будущее, подумай над ленивой генерацией прямоугольников - понятно что для этого в drawer'e придется что-то поменять (возможно не пытаться вписать все облако в bitmap и пусть выходит за границы - тут уже твое дело).
Плохо это тем, что в случае большого количества прямоугольников нужно будет создавать массив большого объема - выделять память. При ленивой ты просто из метода бы доставал прямоугольник друг за другом и ничего бы не выделял.

Еще в чем минус конкретно здесь, это использование ToArray. Этот метод коварен тем, что во время исполнения постоянно будут пересоздаваться массивы -> больше затрат на аллокацию и GC.

Это на самом деле просто оптимизации, которые больше относятся к высокопроизводительному коду, но на такие моменты тоже нужно обращать внимание, чтобы писать код еще эффективнее.

Несмотря на удобства LINQ нужно использовать его с умом и понимать, где это может помешать. Особенное внимание это конечно ToArray, ToList, OrderBy, Distinct и т.д.

2022-11-01 05:42 UTC, closed without merging