Пермяков Роман
kontur-csharper/tdd pull request #140
Opened 2021-11-06 12:31 UTC by Buskervil

@theZeliboba
@HolyPrapor

2021-11-07 07:01 UTC, HolyPrapor requested changes

2021-11-07 07:01 UTC, HolyPrapor commented on cs/BowlingGame/Game.cs
>  namespace BowlingGame
Давай оформим `TagsCloudVisualization` в отдельную папку, да и вообще в отдельный солюшен?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +    internal class ArchimedeanSpiral
Вроде более правильным названием будет `ArchimedesSpiral`, но я не уверен, и это придирки :)

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +        private int _offSetX;
`offset` обычно пишут одним словом, не выделяя в `offSet`

2021-11-07 07:01 UTC, HolyPrapor commented on .gitignore
> +*.png
Кажется, в репозиторий всё равно проникли `.png`. 

Думаю, можно их убрать. Но можно и завести под них отдельную папку, чтобы они играли роль семплов.

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/Program.cs
> +            var spiral = new ArchimedeanSpiral(Point.Empty);
Может быть, неплохо было бы сделать пустой конструктор с дефолтным инициализатором в виде центра?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/Program.cs
> +        static void GenerateTagCloud(int tagsCount)
Может быть подумаем в сторону выноса `Generate` методов в какие-то отдельные классы?

Например, мы можем хотеть генерировать как используя какие-то рандомные размеры, так и имея список размеров заранее

2021-11-07 07:01 UTC, HolyPrapor commented on .gitignore
> +*.png
UPD: ты уже их уничтожил :)

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +        private double _a;
Как насчёт того, чтобы дать этой переменной более понятное название?
С описанием лучше, но может быть что-то вроде `thickness` будет хорошо смотреться?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +                var rho = _phi * _a / (2 * Math.PI);
Думаю, логику преобразования полярных координат в декартовы и обратно можно вынести в отдельный класс.

Так можно будет тесты написать на эти преобразования, и заиспользовать их где-то ещё

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +                _phi += 0.01;
Возможно, было бы прикольно уметь контролировать угол смещения?
Можно не выносить как отдельный параметр в конструктор, а просто как константу приватную в этом классе сделать.

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +            _a = 1;
Можно инициализировать поля сразу же, вне конструктора.

Когда изучаешь чужой код, и смотришь определение класса, не сразу идёшь смотреть конструкторы. 
Было бы удобнее видеть дефолтные значения сразу.

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +    public class CircularCloudLayouter
Может быть выделим интерфейс `ICloudLayouter`?
"Раскладыватели" ведь могут быть не только круговыми

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            _spiral = new ArchimedeanSpiral(center);
Возможно, было бы круто, если бы здесь тоже выделили какой-то `ISpiral`, спирали то тоже разные бывают

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +        public IEnumerable<Point> Slide()
А почему решил такое название для метода выбрать?
Мне оно не слишком понятно, но я кажется что-то упускаю

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        public Size CanvasSize { get => GetCanvasSize(); }
Может это тоже куда-нибудь уберём?
Кажется, что "раскладыватель" не должен думать о размере `Canvas`а

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        public List<Rectangle> Rectangles { get; private set; }
Наверное, не очень хорошо, что это публичная переменная. Вдруг кто-то что-то туда добавит.
Она точно должна быть публичной?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            foreach (var r in Rectangles)
Попробуем переписать этот метод с помощью `LINQ`?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            foreach (var spiralPoint in _spiral.Slide())
Часто, когда я вижу `foreach`, я думаю что этот цикл конечный.
Тут это не так. Не то, чтобы это плохо, но кажется можно чуть аккуратнее переписать через `while` и `MoveNext`.

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +                if (!CheckIntersects(new Rectangle(spiralPoint, rectSize)))
С учётом предыдущего замечания, можно выделить один `rectangle`, и работать только с ним.
Поля `Rectangle.X` и `Rectangle.Y` мутабельные

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/Extensions/PointExtensions.cs
> +        public static Point GetRectangleLocationByCenter(this Point center, Size rectSize) =>
Можно на это тоже тестов добавить, хотя бы парочку.

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +        public static List<int> GetDistancesToPoint(this Rectangle rect, Point point)
Может быть тут лучше будет возвращать не лист, а `NamedTuple`?
Что-то вроде `(Point left, Point top, Point right, Point bottom)`

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +            if (distances.Any(d => d < 0))
Неочевидно, что мы рассматриваем точки только внутри прямоугольника из названия(
Но в описании это есть :)

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +        public static Rectangle GetIntersect(this Rectangle first, Rectangle second)
```suggestion
        public static Rectangle GetIntersection(this Rectangle first, Rectangle second)
```

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +            first.Intersect(second);
а `Intersect` разве не иммутабельный метод?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +            first.Intersect(second);
Мне казалось, что он возвращает новый прямоугольник

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/Program.cs
> +                gr.DrawEllipse(Pens.Red, new Rectangle(point, new Size(1, 1)));
Ручки тоже можно будет вынести в параметр такого класса, если решим убрать эти методы отсюда

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            //if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
Не забывай убирать закомментированный код из PR

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            putRect.Should().Throw<ArgumentException>().Which.Message.Should().StartWith("������������� ������ ��������������");
Это только у меня тут кракозябры в сообщении, или у тебя тоже?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            putRect.Should().Throw<ArgumentException>().Which.Message.Should().StartWith("������������� ������ ��������������");
Точно ли мы хотим явно фиксировать сообщение из эксепшена в тесте?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            putRect.Should().Throw<ArgumentException>().Which.Message.Should().StartWith("������������� ������ ��������������");
Можно ещё протестить случай, когда только ширина или только длина отрицательная

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +                var directory = Directory.GetCurrentDirectory();
Может отдельную папочку сделаем?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +                Console.WriteLine($"{ context.Test.Name} {context.Result.Outcome.Status} - Image Saved");
Тут форматирование потерялось

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            var rectSises = TestHelper.GenerateSizes(10);
```suggestion
            var rectSizes = TestHelper.GenerateSizes(10);
```

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            var mesuresCount = 10;
```suggestion
            var measuresCount = 10;
```

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            elapsed.Should().BeLessThan(5_000 * mesuresCount);
Кажется, тут должно быть 2000?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +        [Test]
Может попробуем воспользоваться аттрибутом `Repeat`?

Там, конечно, не `average` будет, но возможно это не страшно

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +        public void PutRectangles_WithOver75PercentAverageDensity()
Может быть, вынесем количество прямоугольников в параметры, и позапускаем с разным количеством?

А размеры прямоугольников можно не только генерировать, но и протестить на константных размерах

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +        public void PutRectangles_WithOver75PercentAverageDensity()
Следующий метод тогда, возможно, станет ненужным

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            var targetFactor = 0.8;
Кажется, тут должно быть 0.75?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +                var rectSises = TestHelper.GenerateSizes(30);
Может логику добавления "больших размеров" прямо в TestHelper убрать?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/TestHelper.cs
> +        public static Rectangle UnionAll(List<Rectangle> rectangles)
Кажется, где-то я уже видел такой метод :)

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/TestHelper.cs
> +                        var itersect = first.GetIntersect(second);
```suggestion
                        var intersect = first.GetIntersect(second);
```

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/TestHelper.cs
> +                            throw new InvalidOperationException("Был изменен объект вместо создания нового");
Расскажи, для чего нужна эта проверка?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/TestHelper.cs
> +            foreach (var first in rectangles)
Кажется, тут на индексах было бы проще написать?

```
for (var i = 0; i < rectangles.Count; i++)
{
    for (var j = i + 1; j < rectangles.Count; j++)
    {
        var first = rectangles[i];
        var second = rectangles[j]; 
    }
}
```

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/BitmapDrawer.cs
> +            g.Dispose();
`using` ?

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/BitmapDrawer.cs
> +        public static void Save(Bitmap bitmap, string filename = null)
У `Bitmap` есть метод `Save`

Можно писать так: `BitmapDrawer.Draw(layouter).Save("filename");`

Если хочешь уметь подставлять дефолтные имена, то можно в экстеншн вынести

Но это всё на твое усмотрение)

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/BitmapDrawer.cs
> +                var pen = new Pen(color, 0) { Alignment = PenAlignment.Inset };
Было бы прикольно иметь возможность выбирать цвета не только рандомно, но и из какого-то "пула" цветов.
Типа, если бы я тебе дал { красный, синий, желтый }

2021-11-07 07:01 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +                _phi += 0.01;
А у тебя кстати был `deltaAngle`! 

Только ты его почему-то убрал(

2021-11-07 07:10 UTC, Buskervil commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +    internal class ArchimedeanSpiral
![изображение](https://user-images.githubusercontent.com/82332119/140635849-2880a04c-4dce-428d-9842-6c78cf72eba0.png)
Наверное потому, что она не принадлежит Архимеду, а имени Архимеда)

2021-11-07 07:11 UTC, Buskervil commented on cs/TagsCloudVisualization/Program.cs
> +            var spiral = new ArchimedeanSpiral(Point.Empty);
Точно

2021-11-07 07:12 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            //if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
А вообще, надо раскомментировать эту штуку, наверное?

2021-11-07 07:12 UTC, Buskervil commented on cs/TagsCloudVisualization/Program.cs
> +        static void GenerateTagCloud(int tagsCount)
Можно, это я на скорую руку для быстрой проверки результата писал

2021-11-07 07:15 UTC, Buskervil commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +        private double _a;
![изображение](https://user-images.githubusercontent.com/82332119/140636023-d8bf7447-6018-497f-8f18-4be2736e1407.png)
Наверное будет "pitch"

2021-11-07 07:33 UTC, Buskervil commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +                var rho = _phi * _a / (2 * Math.PI);
А она (логика) может еще где-то понадобиться? Да и у спирали не убудет, все равно еще offset-ы прибалять.
Будет служебный класс с парой методов... Хорошо

2021-11-07 07:36 UTC, Buskervil commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +                _phi += 0.01;
Я по разному думал, наверное  самое нормальное - можно его в качестве агрумента передавать, сделать параметр со значением по умолчанию...
Когда делал не понравилось, что такие цифры в CircularCloudLayouter наружу торчат.
Но если со значением по умолчанию, то, наверное, можно.

2021-11-07 07:38 UTC, Buskervil commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +            _a = 1;
Вот тут вопрос: Я почему-то всегда стараюсь явно выписывать конструктор, даже если он без параметров, мне всегда казалось, что так правильнее. Возможно я не прав, как принято?

2021-11-07 07:38 UTC, Buskervil commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +    public class CircularCloudLayouter
Это да

2021-11-07 07:39 UTC, Buskervil commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            _spiral = new ArchimedeanSpiral(center);
Хорошо. Для текущей задачи почти никакая кроме Архимедовой не подходит, но на будущее...

2021-11-07 07:41 UTC, Buskervil commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +        public IEnumerable<Point> Slide()
У меня оно почему-то вызывает визуальный образ "скольжение по спирали". Может это странно). Лучше переименовать?

2021-11-07 07:43 UTC, Buskervil commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        public Size CanvasSize { get => GetCanvasSize(); }
Уже думал над этим, подумаю еще. У него проще всего спросить, потому что у него все данные есть, для его определения. Первая мысль, что придется куда-то передавать лист Rectangles мне не понравилась. Подумаю.

2021-11-07 07:45 UTC, Buskervil commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        public List<Rectangle> Rectangles { get; private set; }
Тут, вроде, все безопасно.
1. public readonly Point Center; - только для чтения readonly 
2. public Size CanvasSize { get => GetCanvasSize(); } - нет сеттера, только для чтения
3. public List<Rectangle> Rectangles { get; private set; } - сеттер есть но приватный.

Все доступно извне, но изменять нельзя.

2021-11-07 07:47 UTC, Buskervil commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            foreach (var spiralPoint in _spiral.Slide())
Да, спасибо! Тоже думал, что это место с подвохом.

2021-11-07 07:48 UTC, Buskervil commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +                if (!CheckIntersects(new Rectangle(spiralPoint, rectSize)))
Не понял

2021-11-07 07:51 UTC, Buskervil commented on cs/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +        public static List<int> GetDistancesToPoint(this Rectangle rect, Point point)
Да, я так и написал сначала. Но у меня везде возврат из этого метода используется примерно так:
`var radius = union.GetDistancesToPoint(center).Average();`
А с кортежем будет не удобно. Компромисс

2021-11-07 07:53 UTC, Buskervil commented on cs/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +            if (distances.Any(d => d < 0))
Можно поправить, но тогда название метода будет длиннющим. В качестве компромисса я написал доки. Лучше переименовать?

2021-11-07 07:56 UTC, Buskervil commented on cs/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +            first.Intersect(second);
Void. Потому и написал такую шутуку. Она работает, потому что Rectangle структура и в метод передается копия.

2021-11-07 07:57 UTC, Buskervil commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            //if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
По условю просят сохранять картинку только для проваленных тестов. Можно оставить для всех?

2021-11-07 09:00 UTC, Buskervil commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            putRect.Should().Throw<ArgumentException>().Which.Message.Should().StartWith("������������� ������ ��������������");
Да, какая-то проблема с кодировкой случилась.
Насчет сообщения, это может быть лишним, но почему бы и нет, может там написано: "Одна из сторон должна быть положительной".

2021-11-07 09:02 UTC, Buskervil commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +                var directory = Directory.GetCurrentDirectory();
Вот тут куча вопросов. Как правильно сохранять? У меня метод bitmap.Save кидает эксепшены, если в него передается что-то кроме имени файла или текущ. директория + имя файла, могу положить файл в корень диска. Создать папку никак не получается. С правами на запись вроде все ок.

2021-11-07 09:07 UTC, Buskervil commented on cs/TagsCloudVisualization_Test/TestHelper.cs
> +        public static Rectangle UnionAll(List<Rectangle> rectangles)
Точно. Не знаю как быть он и там и тут нужен. Ссылаться будет неправильно он вспомогательный.
Наверное тоже можно extensions сделать

2021-11-07 09:11 UTC, Buskervil commented on cs/TagsCloudVisualization_Test/TestHelper.cs
> +                            throw new InvalidOperationException("Был изменен объект вместо создания нового");
Наверное нужно убрать, для себя писал. Хотя она показывает, что я точно не испортил объекты при перечислении и проверяю пересечения адекватно.
Вдруг кто-то испортит extension метод...

2021-11-07 09:12 UTC, Buskervil commented on cs/TagsCloudVisualization/BitmapDrawer.cs
> +            g.Dispose();
Эквивалетные же конструкции? С using придется все еще в 2 скобки обернуть

2021-11-07 16:15 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +    internal class ArchimedeanSpiral
Принято

2021-11-07 16:17 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +        private double _a;
У меня `pitch` ассоциируется с каким-то аудио в первую очередь

Можно назвать `radius`, можно `thickness`, можно ещё как-нибудь.

Я согласен с тем, что часто лучше придерживаться принятых установок, как в математике, но конкретно в этом случае большая часть читателей кода, вероятно, будет не знакома с этими принятыми обозначениями, поэтому их лучше переназвать

Выбери что-нибудь сам)

2021-11-07 16:18 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +                var rho = _phi * _a / (2 * Math.PI);
Может понадобиться, если кто-то решит сделать другую спираль.

Но не забывай, что ещё это для проверки корректности математики: эти методы будут понятные, будет проще читать, и можно будет протестировать их

2021-11-07 16:19 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +                _phi += 0.01;
Эта проблема у тебя исчезнет, если ты выделишь `ISpiral`, и будешь подавать в `CircularCloudLayouter` уже готовую спираль

2021-11-07 16:21 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +            _a = 1;
Думаю зависит от команды.

У меня принято опускать такие конструкторы, если там просто инициализация значений, и их можно раскидать по полям.

2021-11-07 16:21 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +            _a = 1;
Конкретно в этом случае тут ничего хитрого - можно просто дефолты у полей расставить - будет чисто :)

2021-11-07 16:22 UTC, HolyPrapor commented on cs/TagsCloudVisualization/ArchimedeanSpiral.cs
> +        public IEnumerable<Point> Slide()
Если не смотреть на сигнатуру метода, можно даже предположить, что он `void`, и как-то там двигает спиральку

Может лучше что-нибудь вроде `GetSpiralPoints`?

2021-11-07 16:25 UTC, HolyPrapor commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        public Size CanvasSize { get => GetCanvasSize(); }
Думаю, что эта проблема тоже уйдет, если `BitmapDrawer` не будет принимать `ILayouter`, а будет брать список прямоугольников и просто их рисовать.

А список прямоугольников можно аггрегировать где-то в другом месте

Но можно и по-другому декомпозировать - придумай что-нибудь :)

2021-11-07 16:27 UTC, HolyPrapor commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        public List<Rectangle> Rectangles { get; private set; }
Не совсем.
`Rectangles` хранит ссылку на `List`, так как это класс. И ссылку действительно подменить нельзя - сеттер приватный.
Однако ничего не мешает вызывать методы списка: `Add` или даже `Clear`.

2021-11-07 16:28 UTC, HolyPrapor commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +                if (!CheckIntersects(new Rectangle(spiralPoint, rectSize)))
Здесь ты на каждой итерации создаёшь новый `Rectangle`, а можно сделать это только один раз

На самом деле это супер минорное замечание, можно закрыть на него глаза)

2021-11-07 16:29 UTC, HolyPrapor commented on cs/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +        public static List<int> GetDistancesToPoint(this Rectangle rect, Point point)
Ок, думаю, в таком случае это уместно.

2021-11-07 16:29 UTC, HolyPrapor commented on cs/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +            if (distances.Any(d => d < 0))
Как насчёт `GetDistancesToInnerPoint`?

2021-11-07 16:30 UTC, HolyPrapor commented on cs/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +            first.Intersect(second);
Ок, принято.

2021-11-07 16:30 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            //if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
Не так важно, давай просто раскомментируем строчку

2021-11-07 16:32 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            putRect.Should().Throw<ArgumentException>().Which.Message.Should().StartWith("������������� ������ ��������������");
Это имеет смысл, если мы хотим чётко фиксировать, в чём проблема входных данных

Вроде не очень подходит под наш случай, но я не настаиваю)

2021-11-07 16:32 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +                var directory = Directory.GetCurrentDirectory();
Ответил в личке

2021-11-07 16:33 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/TestHelper.cs
> +        public static Rectangle UnionAll(List<Rectangle> rectangles)
Или экстеншн, или ещё один вспомогательный класс, хорошая идея)

2021-11-07 16:34 UTC, HolyPrapor commented on cs/TagsCloudVisualization_Test/TestHelper.cs
> +                            throw new InvalidOperationException("Был изменен объект вместо создания нового");
Я не до конца понимаю природу "испортил объекты". Ты про метод `GetIntersect`?
Если хочется убедиться в его корректности, для этого всегда можно тесты написать прямо на него)

2021-11-07 16:35 UTC, HolyPrapor commented on cs/TagsCloudVisualization/BitmapDrawer.cs
> +            g.Dispose();
Да, эквивалентные

На мой вкус с `using` было бы чище, но да, увеличивается вложенность. Решай сам, как оставить)

2021-11-08 11:29 UTC, Buskervil commented on cs/TagsCloudVisualization_Test/TestHelper.cs
> +                            throw new InvalidOperationException("Был изменен объект вместо создания нового");
Про "испортил объекты": тут речь о том, что Intersect стандартный меняет текущий объект, получается, что если объект был изменен, то последующие проверки будут неадекватны.

2021-11-09 14:34 UTC, HolyPrapor approved these changes

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/DemoImageGenerator.cs
> +        public static void GenerateTagCloud(int tagsCount, Spiral spiral)
А если я хочу не круговой раскладыватель? Может в этих методах лучше принимать `CloudLayouter`?

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +        public static Rectangle GetIntersection(this Rectangle first, Rectangle second)
Дело вкуса, но может здесь бы лучше сработало что-то вроде `TryGetIntersection`?

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/Program.cs
> +        public static void Main()
В идеале тут прям хотелось бы видеть код, который требуется по заданию: генерация раскладок с разными параметрами. 
Например, попробовать погенерировать прямоугольники с площадью от 10 до 150, и рядом такие же, но с площадью от 15 до 25, чтобы сравнить плотность.
Тут же ещё посмотреть на разный `deltaAngle` спирали, или попровать выбрать другой центр.
Твой код всё это умеет, нужно только аккуратно всё вынести в удобные методы :)

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/TagCloudDrawer.cs
> +        public static Bitmap Draw(IEnumerable<Rectangle> rectangles, Point center, List<Color> colors = null)
Кажется, что сюда ещё было бы неплохо перенести методы отрисовки спирали (они почему-то остались в `DemoImageGenerator`.

А ещё, возможно, этот класс был бы лучше, если бы методы были не статическими, а параметры отрисовки мы бы могли передать в его конструктор, что думаешь?

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/TagCloudDrawer.cs
> +        public static void Save(Bitmap bitmap, string filename = null)
Честно говоря, я думаю, что лучше бы это было экстеншном, а не статическим методом в "отрисовщике".

Было бы круто если бы получился fluent-like интерфейс `drawer.Draw(rectangles).Save("onBigRectangleDifference.png")`

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/Spiral.cs
> +        public void SetCenter(Point center)
А нужно ли нам менять центр после инициализации спирали?
Расскажи, для чего?

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/Spiral.cs
> +        protected double Radius;
Я бы все эти параметры занёс в архимедову спираль. Не факт, что все спирали будут считаться в полярных координатах.

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/Spiral.cs
> +        protected double Radius;
А вот центр принимать - это норм

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization_Test/ArchimedeanSpiral_Test.cs
> +        public void Should_SetCenter_InEmptyCounstryctor_AsEptyPoint()
Тут как будто дислексия произошла))

Поправишь опечатки?

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization_Test/ArchimedeanSpiral_Test.cs
> +            var point = spiral.GetDiscretePoints().Take(1).First();
А нужно `Take(1)` делать перед `First`?

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization_Test/ArchimedeanSpiral_Test.cs
> +                var lastFurtherThanFirst = Math.Abs(points.First().X) < Math.Abs(points.Last().X)
А чего эта переменная не используется?

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization_Test/ArchimedeanSpiral_Test.cs
> +                var lastFurtherThanFirst = Math.Abs(points.First().X) < Math.Abs(points.Last().X)
Если хотелось сделать понятнее, что происходит ниже, можно было сделать метод (можно даже локальный метод)

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization_Test/CoordinatesConverter_Test.cs
> +            var polar = CoordinatesConverter.ToPolar(new Point(x, y));
В таких местах можно деконструктор использовать

```suggestion
            var (rho, phi) = CoordinatesConverter.ToPolar(new Point(x, y));
```

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization_Test/RectangleExtensions_Test.cs
> +            var expected = new List<int> { 50, 50, 50, 50 };
Тоже не используется(

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization_Test/CircularCloudLayouter_Test/PutNextRectangle_Should.cs
> +            new CircularCloudLayouter(center ?? Point.Empty, new ArchimedeanSpiral(center.Value));
Тут аргумент спирали забыл проинициализировать

`center.Value ?? Point.Empty`

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/TagCloudDrawer.cs
> +                foreach (var rect in rectangles)
Ты тут дважды пробегаешься по `IEnumerable`.

У тебя везде списки - и тебя это не аффектит, но если кто-то подаст на вход честный `IEnumerable` - всё развалится(

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/TagCloudDrawer.cs
> +                foreach (var rect in rectangles)
Аналогично в `GetCanvasSize` то же самое происходит

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/Program.cs
> +        public static void Main()
Было бы круто если бы было что-то подобное:
```
var drawer = new TagCloudDrawer(<optional parameter colors / pens>);
drawer.Draw(DemoImageGenerator.GenerateCircularLayout(<either spiral or spiral parameters>, <rectSizes>, <amount>)).Save("WithLotsOfSmallRectangles");
drawer.Draw(DemoImageGenerator.GenerateCircularLayout(<either spiral or spiral parameters>, <rectSizes>, <amount>)).Save("WithLotsOfBigRectangles");
```

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/DemoImageGenerator.cs
> +        public static void GenerateTagCloud(int tagsCount, Spiral spiral)
Ещё есть вариант переименовать в `CircularTagCloud`

Но общий метод для произвольного раскладывателя всё равно нужен

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/CloudLayouter.cs
> +        protected private List<Rectangle> _rectangles;
Тут, наверное, просто `protected`?

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/CircularCloudLayouter.cs
> +            while (pointEnumerator.MoveNext())
Выглядит уже почти идеально!
Есть финальное предложение. 
Так как у тебя спираль бесконечная by design, проверять наличие элемента смысла особого нет, поэтому можно написать что-то такое

```
while (rectangles.Any(x => x.IntersectsWith(rect)))
{
    pointEnumerator.MoveNext();
    dryRect.Location = pointEnumerator.Current;
}
```

2021-11-09 14:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/CloudLayouter.cs
> +        public List<Rectangle> Rectangles { get => _rectangles.ToList(); }
```suggestion
        public List<Rectangle> Rectangles => _rectangles.ToList();
```

2021-11-09 16:56 UTC, Buskervil commented on TagsCloudVisualization/TagsCloudVisualization/TagCloudDrawer.cs
> +        public static void Save(Bitmap bitmap, string filename = null)
Тут только ради счетчика оставил, ну и переписал по-аккуратнее. Чтобы если упало несколько тестов было что-то типа 01_failed.png, 02_failed.png

2021-11-09 16:58 UTC, Buskervil commented on TagsCloudVisualization/TagsCloudVisualization/Spiral.cs
> +        public void SetCenter(Point center)
Не знаю как отслеживать согласованность центров спирали и layouter-а, если мы ему через конструктор готовую передаем. Надеятся, что вызывающий код все сделал правильно? На всякий случай сделал метод "принудительной" установки центра. Но опять же, через него при желании можно все испортить...

2021-11-09 16:59 UTC, Buskervil commented on TagsCloudVisualization/TagsCloudVisualization_Test/ArchimedeanSpiral_Test.cs
> +            var point = spiral.GetDiscretePoints().Take(1).First();
Конечно нет)

2021-11-09 17:02 UTC, Buskervil commented on TagsCloudVisualization/TagsCloudVisualization/CloudLayouter.cs
> +        protected private List<Rectangle> _rectangles;
Специально написал, вроде работает как надо
- private скрывает доступ из всех классов
- protected открывает доступ наследникам.
Может ошибаюсь

2021-11-10 08:28 UTC, Buskervil commented on TagsCloudVisualization/TagsCloudVisualization/DemoImageGenerator.cs
> +        public static void GenerateTagCloud(int tagsCount, Spiral spiral)
Подумал. 
Сейчас это метод занимается конфигурацией layoutera и потом передает прямоугольники TagCloudDrawer. Чтобы сделать его универсальным конфигурацию надо будет унести в вызывающий код. Тогда из полезного в методе останется только генерация прямоугольников.
Другим layoter-ам может быть не нужна спираль, может быть нужно что-то другое или не нужно ничего.

Я могу написать общий метод примерно так:
```
        public static void GenerateTagCloud(CloudLayouter layouter, int tagsCount)
        {
            var rectSizes = new List<Size>();
            var rnd = new Random();
            for (int i = 0; i < tagsCount; i++)
            {
                var width = rnd.Next(14, 60);
                var height = rnd.Next(10, width);
                rectSizes.Add(new Size(width, height));
            }
            GenerateTagCloud(layouter, rectSizes);
        }

        public static void GenerateTagCloud(CloudLayouter layouter, IEnumerable<Size> rectSizes)
        {
            rectSizes.ToList().ForEach(s => layouter.PutNextRectangle(s));
            using (var bitmap = TagCloudDrawer.Draw(layouter.Rectangles, layouter.Center))
                TagCloudDrawer.Save(bitmap);
        }
```
Но удобно ли будет им пользоваться? Мне кажется, проще будет воспользоваться напрямую открытыми классами layouter-ов и TagCloudDrawer.

2021-11-10 08:42 UTC, Buskervil commented on TagsCloudVisualization/TagsCloudVisualization/Spiral.cs
> +        public void SetCenter(Point center)
Можно, наверное, еще Exception бросать, если центры не совпадают.

2021-11-10 08:46 UTC, Buskervil commented on TagsCloudVisualization/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +        public static Rectangle GetIntersection(this Rectangle first, Rectangle second)
Имеешь в виду метод с out параметром сделать?

2021-11-10 08:51 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/Extensions/RectangleExtensions.cs
> +        public static Rectangle GetIntersection(this Rectangle first, Rectangle second)
Ага

2021-11-10 08:51 UTC, Buskervil commented on TagsCloudVisualization/TagsCloudVisualization/TagCloudDrawer.cs
> +        public static Bitmap Draw(IEnumerable<Rectangle> rectangles, Point center, List<Color> colors = null)
Мне кажется, тут примерно равно? В некоторых случаях будет удобнее воспользоваться статикой без создания экземпляров. А где-то удобно было бы с одинаковыми параметрами генерить картинки через объект.

Может просто добавит еще и динамические методы и как-нибудь делегировать уже написанным?

2021-11-10 08:52 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/CloudLayouter.cs
> +        protected private List<Rectangle> _rectangles;
А как работает `protected` без `private`?

Советую ещё прочитать про `private protected` отдельно (никогда не использовал и не видел его в реальном коде, честно говоря)

2021-11-10 08:53 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/Spiral.cs
> +        public void SetCenter(Point center)
А нам вообще нужно два центра: и там и там?
Может, только в спирали оставим?

2021-11-10 08:54 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/TagCloudDrawer.cs
> +        public static void Save(Bitmap bitmap, string filename = null)
Ну счётчик и в экстеншн классе может быть ведь)

2021-11-10 08:58 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/DemoImageGenerator.cs
> +        public static void GenerateTagCloud(int tagsCount, Spiral spiral)
Да, возможно, такой метод и не нужен.

По-хорошему, наверное, хранить прямоугольники - это не ответственность `Layouter`а. Он их просто раскладывает. Но из-за внутренних причин реализации, получилось, что они ему нужны для проверки пересечений.

И получается, что `Layouter`у обёртка никакая и не нужна.

2021-11-10 09:00 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/DemoImageGenerator.cs
> +        public static void GenerateTagCloud(int tagsCount, Spiral spiral)
Но всё равно удобно иметь методы вроде `GenerateCircularTagCloud`, чтобы не париться с их настройкой.

А общий метод тогда не будем делать

2021-11-10 09:02 UTC, Buskervil commented on TagsCloudVisualization/TagsCloudVisualization/CloudLayouter.cs
> +        protected private List<Rectangle> _rectangles;
Ты прав, я что-то перепутал, protected достаточно
![изображение](https://user-images.githubusercontent.com/82332119/141082114-e31ee31b-2e5e-43ed-b6c8-fc452617cd1d.png)

2021-11-10 09:35 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/TagCloudDrawer.cs
> +        public static Bitmap Draw(IEnumerable<Rectangle> rectangles, Point center, List<Color> colors = null)
Это не всегда верно, так как отрисовщик может приходить откуда-то извне, и он будет удобным "контейнером" для параметров отрисовки в таком случае.
А то если ты захочешь контролировать еще какие-то детали, придётся их во все методы прокидывать - это неудобно и плохо расширяемо.
В конечном итоге ты захочешь либо вынести всё в какой-то `DrawSettings` (можно так сделать и сейчас), либо сделать класс нестатическим.
Тут уже дело вкуса)

2021-11-13 04:14 UTC, Buskervil commented on TagsCloudVisualization/TagsCloudVisualization/TagCloudDrawer.cs
> +        public static void Save(Bitmap bitmap, string filename = null)
Вынес. Но с fluent-like наверное не получится, потому что где-то надо освобождать памать от картинки, мне кажется лучше это делать явно. Т.к. не очевидно было бы если бы она уничтожалась после сохранения.

2021-11-13 04:21 UTC, Buskervil commented on TagsCloudVisualization/TagsCloudVisualization/TagCloudDrawer.cs
> +        public static Bitmap Draw(IEnumerable<Rectangle> rectangles, Point center, List<Color> colors = null)
Drawer у меня уже несколько коммитов существует как TagCloudDrawer, наверное, отрисовку спирали не буду туда складывать. Метод для спирали был для понимания процесса, мне кажется, ничего плохого нет в том что он лежит в DemoImageGenerator, т.к. для корректной работы задачи он не нужен.

2021-11-14 07:41 UTC, HolyPrapor approved these changes
LGTM! Great job!

2021-11-14 07:41 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/ArchimedeanSpiral.cs
> +        protected double Radius;
А чего они protected-то?
Приватные получше по смыслу подходят ведь)

2021-11-14 07:41 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/Program.cs
> +        public static List<Size> GetRandomSizesWithArea(List<int> areas, int amount)
Лично я бы вынес этот код в какой-нибудь `RandomRectangleGenerator` и звал бы оттуда эти методы, чтобы не мешались, но можно и так

2021-11-14 07:41 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/Program.cs
> +            DemoImageGenerator.GenerateCircularTagCloud(GetRandomSizesWithArea(3000, 600),
Ну и всё-таки имя файла потерялось, так сходу не вчитываясь не понять, что генерируется. А по именам файлов было бы прям удобно.

Но всё равно чисто!

2021-11-14 08:34 UTC, HolyPrapor commented on TagsCloudVisualization/TagsCloudVisualization/ArchimedeanSpiral.cs
> +        private double Radius;
а если они приватные, то у тебя по кодстайлу имена тогда на `_radius` и `_phi` смениться должны))

2022-11-01 05:42 UTC, closed without merging