Суримов Максим
kontur-csharper/tdd pull request #141
Opened 2021-11-06 13:49 UTC by MaxxLorge

@orange-bird

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/RecatngleExtensions.cs
> +    public static class RecatngleExtensions
В названии класса (и файла) опечатка

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/RecatngleExtensions.cs
> +using System.Threading.Tasks;
Неиспользуемые using лучше удалять.

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/RecatngleExtensions.cs
> +
Лишние строки никому не нужны - лучше от них избавляться

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/RecatngleExtensions.cs
> +        public static bool IntersectWith(this IEnumerable<Rectangle> rects, Rectangle rect) => rects.Any(r => r.IntersectsWith(rect));
Я бы сказал, что этот метод должен применяться к прямоугольнику, а не к их набору, потому что именно для него мы тестируем пересечения, а не для набора.

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/RecatngleExtensions.cs
> +    public static class RecatngleExtensions
И еще я бы подумал над тем, чтобы сделать этот класс `internal`, т.к. не вижу в нем смысла вне этого проекта.

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +        [TestCase(0,3, TestName = "width is zero")]
Название тесткейсов в принципе правильное, но когда смотришь на результаты их выполнения, то видишь простое `width is zero` и не понимаешь, что именно тут тестируется - конструктор? размер прямоугольника? что-то еще?

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +        [TestCase(100)]
Есть ли необходимость в 4 похожих кейсах?

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +        [TestCase(100)]
Снова - есть ли необходимость в разном количестве? Разве сценарий с 100 прямоугольниками не будет выключать в себя меньшие по количеству проверки?

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +            act.ExecutionTime().Should().BeLessOrEqualTo(new TimeSpan(0,0,0,5));
Лучше ли это задания таймаута атрибутом, как это сделано в предыдущем тесте?

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/SpiralPointsCreator.cs
> +                var newX = (Center.X + radiusVector * Math.Cos(currentAngle));
Лишние скобки

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +        public BitmapVisualizer(int width, int height)
Где проверка на размеры? Что, если я передам в конструктор отрицательные значения?

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            bmp = new Bitmap(width, height);
Насколько я помню, и `Bitmap`, и `Graphics` реализуют `IDisposable`. Давай что-то с этим сделаем?

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            layouter = new CircularCloudLayouter(new Point(Width / 2, Height / 2));
Мне кажется не очень хорошей идеей создавать layouter внутри средства для рисования. Кажется, что зависимость должна быть в обратную сторону. Конечно, я немного забегаю вперед - это в целом будет рассматриваться в рамках задачи Tag Cloud 2, но лучше уже сейчас это сделать, чтобы потом не переписывать.

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +        public void GenerateRandomRectangles(int count)
Не вижу смысла в данном методе. Если он когда-то и может применяться, то только в рамках каких-то тестов. В самом проекте-библиотеке, которая выполняет что-то полезное - нет.

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +        public void GenerateRandomRectangles(int count)
Вообще, я немного не понял смысла этого класса в нынешнем его виде. Как будто это просто демо-версия чего-то - делает само, для себя и по своим правилам. Хоть как-то это использовать из другого кода невозможно.

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization_should/SpiralPointsCreator_Should.cs
> +            var creator = new SpiralPointsCreator(new Point(0, 0));
Я бы лучше проверял такие вещи на значениях, отличных от 0. 0 - это значение по умолчанию при создании переменной типа int. Велика вероятность, что даже когда мы что-то где-то забыли присвоить, оно останется верным.

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization_should/SpiralPointsCreator_Should.cs
> +            creator.Center.Should().Be(new Point(0, 0));
Лучше сравнивать не со значением, созданным заново, а с тем, которые мы передавали в конструктор ранее, то есть с тем же экземпляром `Point`.

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization_should/SpiralPointsCreator_Should.cs
> +using TagsCloudVisualization;
Все using не по порядку. Так не годится - любой наставник, глядя на это, может просто отказаться смотреть код вообще.

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization_should/SpiralPointsCreator_Should.cs
> +        [TestCase(100)]
Снова куча тестов одного и того же. Мы не соревнуемся в количестве тесткейсов :)

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +    public class CircularCloudLayouter_Should
Я бы еще предложил написать тест на компактность расположения прямоугольников

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/Program.cs
> +            bmpVisualizer.SaveToFile($"{count}-randomRectangles.png");
Где вообще будет расположен файл-результат? Что будет, если на создание файла не хватает прав доступа?

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +                var width = rnd.Next(50, 60);
Слишком похожий random :) Может, больший диапазон задать? Чтобы это было больше похоже на прямоугольники, а не квадраты? В исходном задании написано про слова. Они редко бывают из 2-3 букв, а гораздо чаще - достаточно длинные.

2021-11-07 06:46 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            graphics.DrawRectangles(new Pen(outlineColor), rectangles);
Может, переиспользовать `Pen`? Сейчас это выглядит как бездумное использование ресурсов.

2021-11-11 08:28 UTC, orange-bird commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +            act.ExecutionTime().Should().BeLessOrEqualTo(new TimeSpan(0,0,0,5));
Вообще, это был скорее вопрос, чем руководство к действию, но окей...

2021-11-11 08:54 UTC, orange-bird requested changes

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            this.rectangles = rectangles ?? throw new ArgumentNullException();
Эти 2 строчки выглядят странно. Как будто они должны выполняться в обратном порядке.

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            rectanglesContainer = rectangles.GetRectanglesContainer();
А нужно ли выполнять все эти шаги в конструкторе? Зачем создавать все эти ресурсы, если я, допустим, ни разу не вызову метод Draw/Save/whatever?

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            bmp?.Dispose();
Если все эти объекты всегда создаются в консктрукторе, то зачем тут проверка на null? Оно же всегда будет не-null.

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            return new Size(rectanglesContainer.Width + 200, rectanglesContainer.Height + 200);
Почему 200?
И даже если 200, почему это не в константах?

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +                throw new AccessViolationException("can't write to this directory");
`AccessViolationException` обычно используется для случаев неудачной попытки записи/чтения памяти. Это не то же самое, что отсутствие доступа.
Вообще, когда я спрашивал про то, что будет при отсутствии прав на запись файла, я подразумевал, что это просто лучше обработать каким-то образом. Или вообще не обработать, если не необходимо, но разъяснить, что будет в этом случае.
Вообще, реализованная проверка доступа - это серьезный подход. Молодец, что разобрался.

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            pen.Color = outlineColor;
Зачем в конструкторе создается Pen со своим цветом, а тут оно меняется?

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        public List<Rectangle> Rectangles { get; }
А зачем это `public`? Есть необходимость? Аналогичный вопрос про `Center`.

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization/DirectoryInfoExtensions.cs
> +            var NtAccountName = $"{Environment.UserDomainName}\\{Environment.UserName}";
У меня тут всего один вопрос, который с каждым годом будет становиться актуальнее - а что, если ОС - не Windows?

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization/Program.cs
> +            bmpVisualizer.Dispose();
Лучше использовать `using`. Ну или полную форму с try-finally, чтобы гарантированно *убивать* unmanaged-ресурсы.

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization/RectangleExtensions.cs
> +            var leftXCoordinate = rectangles.Min(rect => rect.Left);
Во всех методах, даже вспомогательных, лучше предполагать, что может быть передано что-то плохое, и проверять эти ситуации. Как в данном случае - должна быть проверка на наличие в коллекции хотя бы одного элемента, иначе будет исключение при вызове Max/Min.

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization/SpiralPointsCreator.cs
> +                var radiusVector = currentAngle;
В чем смысл отдельной переменной `radiusVector`?

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +                ;
Лишнее

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +            layouter.PutNextRectangle(new Size(5, 5)).Should().Be(new Rectangle(center, size));
Повторение `new Size(5, 5)`. Кажется, что нужно переиспользовать `size`.

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +            var rnd = new Random();
При достаточно быстром (или параллельном) выполнении тест-метода `Random` при таком использовании будет выдавать одни и те же значения.

2021-11-11 08:54 UTC, orange-bird commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +            TestContext.WriteLine($"����������� ���������: {densityCoeff}");
Мне кажется, тут кодировка не UTF8, поэтому в GitHub все отображается кракозябрами.

2021-11-11 09:00 UTC, MaxxLorge commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +                throw new AccessViolationException("can't write to this directory");
Проблема в том, что при недостаточных правах на запись bmp.Save выдает какое-то общее исключение, которое никак не связана с доступом.

2021-11-11 09:10 UTC, MaxxLorge commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        public List<Rectangle> Rectangles { get; }
Rectangles используется снаружи класса. Center можно сделать приватным.

2021-11-11 09:11 UTC, MaxxLorge commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +                ;
Что именно?

2021-11-11 18:48 UTC, MaxxLorge commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            rectanglesContainer = rectangles.GetRectanglesContainer();
Сделал так, чтобы Pen и Graphics создавались и освобождались только в методе DrawRectangles. Создание Bitmap оставил в конструкторе, так как используется в нескольких методах, освобождение ресурсов Bitmap оставил в методе Dispose.

2021-11-11 18:49 UTC, MaxxLorge commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            bmp?.Dispose();
Оставил в Dispose только Bitmap. Убрал проверку на null.

2021-11-11 18:55 UTC, MaxxLorge commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            return new Size(rectanglesContainer.Width + 200, rectanglesContainer.Height + 200);
Убрал в константу. 200 показалось оптимальным отступом от прямоугольников, чтобы они не были впритык к границам изображения.

2021-11-11 18:57 UTC, MaxxLorge commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +                throw new AccessViolationException("can't write to this directory");
Поменял на try catch. Теперь, при неудачной попытке сохранения, будет выводится сообщение о неудачном сохранении, вместо неинформативной ошибки, которую кидал Bitmap.

2021-11-11 18:58 UTC, MaxxLorge commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            pen.Color = outlineColor;
Теперь Pen создается и освобождается внутри данного метода.

2021-11-11 19:00 UTC, MaxxLorge commented on cs/TagsCloudVisualization/DirectoryInfoExtensions.cs
> +            var NtAccountName = $"{Environment.UserDomainName}\\{Environment.UserName}";
Убрал данное расширение DirectoryInfo.

2021-11-11 19:05 UTC, MaxxLorge commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        public List<Rectangle> Rectangles { get; }
Center не нужен - удалил свойство.

2021-11-11 19:08 UTC, MaxxLorge commented on cs/TagsCloudVisualization/Program.cs
> +            bmpVisualizer.Dispose();
Использовал using

2021-11-11 19:12 UTC, MaxxLorge commented on cs/TagsCloudVisualization/RectangleExtensions.cs
> +            var leftXCoordinate = rectangles.Min(rect => rect.Left);
Добавил проверку

2021-11-11 19:18 UTC, MaxxLorge commented on cs/TagsCloudVisualization/SpiralPointsCreator.cs
> +                var radiusVector = currentAngle;
Чисто семантический. При создании спирали у меня длина радиус-вектора равна углу, но дальше идет подсчет новых координат x и y очередной точки (т.е перевод из полярных координат в декартовы), и в этой формуле было бы странно увидеть угол на том месте, где должен быть радиус-вектор.

2021-11-11 19:50 UTC, MaxxLorge commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +            var rnd = new Random();
![image](https://user-images.githubusercontent.com/65601434/141359583-663b6f91-0e32-48ad-8f65-191ff2cb13a5.png)
Ну, в данном случае хотелось проверить на случайных наборах. Да и плотность расположения разная в результатах теста, значит значения разные генерируются.

2021-11-12 07:14 UTC, orange-bird requested changes

2021-11-12 07:14 UTC, orange-bird commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        public List<Rectangle> Rectangles { get; }
Каким образом `Rectangles` используется вне класса? Зачем?
К слову, что будет, если я в этот список извне добавлю еще прямоугольников или удалю часть из существующих?

2021-11-12 07:14 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            if (scale <= 0) throw new ArgumentException("scale should be positive");
А нужно ли что-то делать, если `scale == 1`?

2021-11-12 07:14 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            using (var graphics = Graphics.FromImage(result))
Есть альтернативный вариант: `new Bitmap(bmp, new Size(...))`

2021-11-12 07:14 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +        public void Save(string fileName, double scaleCoeff = 1, DirectoryInfo dir = null)
Что будет, если я вызову этот метод, не вызвав предварительно `DrawRectangles`? Изображение же будет пустым.

2021-11-12 07:14 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            rectanglesContainer = rectangles.GetRectanglesContainer();
Что будет, если создать `BitmapVisualizer`, а потом изменить набор прямоугольников или их позиции/размеры? Правильно ли вычислять размер и выполнять `OffsetRectanglesToCenter` тут?

2021-11-12 07:14 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +                    throw new Exception($"Can't save file to: {path}");
Лучше делать иначе:
```
catch (Exception ex)
{
  throw new Exception($"Can't save file to: {path}", ex);
}
```
чтобы не терять исходное исключение.

2021-11-12 07:14 UTC, orange-bird commented on cs/TagsCloudVisualization/RectangleExtensions.cs
> +            var leftXCoordinate = rectangles.Min(rect => rect.Left);
И я бы еще проверку на null добавил.

2021-11-12 07:14 UTC, orange-bird commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +            var rnd = new Random();
Запусти у себя подобное:
```
var r = new Random();
Console.WriteLine(r.Next(100));
var r2 = new Random();
Console.WriteLine(r2.Next(100));
```
и расскажи, что получилось.

2021-11-12 22:31 UTC, MaxxLorge commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            rectanglesContainer = rectangles.GetRectanglesContainer();
1) Будет плохо. Речь же про то, что аргумент конструктора и поле класса - один и тот же объект? В конструкторе сделал вызов `ToArray()`, чтобы извне нельзя было поменять массив прямоугольников.
2) Не совсем, наверное. Но исходя из других замечаний, снова поменял этот класс, так что теперь:

- Bitmap и Graphics инициализируются только при вызове `DrawRecatangles()`.
- Сдвиг прямоугольников к центру тоже.
-  DrawRectangles теперь можно использовать несколько раз. Например, если хотим другой фон или цвет прямоугольников.
-  Save выдаст исключение, если не был вызван DrawRectangles хотя бы раз.

2021-11-12 22:34 UTC, MaxxLorge commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +            var rnd = new Random();
Получилось два одинаковых числа.

2021-11-12 22:54 UTC, MaxxLorge commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            if (scale <= 0) throw new ArgumentException("scale should be positive");
Не нужно. Вынес это условие в метод Save, т.к метод Resize возвращает новое значение Bitmap, а при scale == 1 это бессмысленно.

2021-11-12 23:06 UTC, MaxxLorge commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            using (var graphics = Graphics.FromImage(result))
Есть ощущение, что теперь этот метод не нужен, но все же оставлю, так как тут подсчет ширины и высоты с помощью scale выполняется, да и приведение типов. Не хочется это в Save переносить.

2021-11-12 23:06 UTC, MaxxLorge commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +        public void Save(string fileName, double scaleCoeff = 1, DirectoryInfo dir = null)
Исправил

2021-11-13 08:34 UTC, orange-bird commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        public Rectangle[] GetRectangles() => rectangles.ToArray();
Вообще, тут тоже непонятна необходимость. Метод `PutNextRectangle` уже возвращает прямоугольник и вызывающий может их у себя где-то складировать. Но текущий вариант тоже имеет место быть.

2021-11-13 08:35 UTC, orange-bird commented on cs/TagsCloudVisualization_should/CircularCloudLayouter_Should.cs
> +using System;
`System.XXXXXX` лучше быть в начале

2021-11-13 08:44 UTC, orange-bird commented on cs/TagsCloudVisualization/BitmapVisualizer.cs
> +            graphics = graphics ?? Graphics.FromImage(bmp);
Обговорили голосом

2021-11-14 04:08 UTC, orange-bird approved these changes

2022-11-01 05:43 UTC, closed without merging