Недугов Владимир
kontur-csharper/tdd pull request #172
Opened 2022-11-06 19:12 UTC by Gorbacheb

@Leoltron

2022-11-08 13:28 UTC, Leoltron requested changes
В целом классно, но кое-какие правки нужно сделать, чтобы было 3 балла в итоге. Предпроверка зачтена.

2022-11-08 13:28 UTC, Leoltron commented on cs/TagsCloudVisualizationTests/CircularCloudLayouterTests.cs
> +        [Test, Category("MustDraw")]
Странная категория, если не знать условие задачи, сложно понять, о чем идет речь.

2022-11-08 13:28 UTC, Leoltron commented on cs/TagsCloudVisualizationTests/CircularCloudLayouterTests.cs
> +            rectangles = new();
Лучше так не делать, нужно идти в определение поля, чтобы догадаться о типе создаваемого объекта.

2022-11-08 13:28 UTC, Leoltron commented on cs/TagsCloudVisualizationTests/CircularCloudLayouterTests.cs
> +                    closerRectangle.X += Math.Sign(Center.X - rectangle.Center().X);
Что проверяет этот тест? Твой генератор дает прямоугольники от размером более 20, если сместить его копию на 1 по любой оси в любую сторону, то она всегда будет пересекаться с исходным.

2022-11-08 13:28 UTC, Leoltron commented on cs/TagsCloudVisualizationTests/CircularCloudLayouterTests.cs
> +                    var res = closerRectangle.IntersectsWith(rectangles);
Что такое `res`?

2022-11-08 13:28 UTC, Leoltron commented on cs/TagsCloudVisualizationTests/CircularCloudLayouterTests.cs
> +            rectangles.Clear();
Зачем эта строка?

2022-11-08 13:28 UTC, Leoltron commented on cs/TagsCloudVisualizationTests/CircularCloudLayouterTests.cs
> +        public void PutNextRectangle_ShouldThrowsException_WhenRectangleSizeBiggerThanCanvas()
nit: should throw

2022-11-08 13:28 UTC, Leoltron commented on cs/TagsCloudVisualizationTests/SpiralTests.cs
> +        [Test, Timeout(1500)]
Если тебя беспокоит таймаут, может, стоит сделать отдельный тест, который будет проверять именно это? А то получается, у тебя тесты проверяют несколько вещей сразу.

2022-11-08 13:28 UTC, Leoltron commented on cs/TagsCloudVisualization/Structures/QuadTree.cs
> +    public class QuadTree
Выглядит сложно, не хочешь написать тесты на эту структуру?

2022-11-08 13:28 UTC, Leoltron commented on cs/TagsCloudVisualization/Structures/QuadTreeNode.cs
> +                    count += node.Count;
Можно переписать на LINQ

2022-11-08 13:28 UTC, Leoltron commented on cs/TagsCloudVisualization/Structures/QuadTreeNode.cs
> +                    return true;
Тоже в LINQ бы обернуть

2022-11-08 13:28 UTC, Leoltron commented on cs/TagsCloudVisualization/Structures/QuadTreeNode.cs
> +        public bool Query(Rectangle queryArea)
Не понятно, что имеется в виду под `Query`, запрос, это очень общее понятие.

2022-11-08 13:28 UTC, Leoltron commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            canvas = GetRectangleAtPositionOfCenter(center, 2 * new Size(center));
Это поведение весьма неочевидно для человека, который видит лишь публичный интерфейс класса. Пользователь захочет своё облако в центре (0, 0) и при первой же вставке получит Exception "Rectangle was placed out side of canvas". Даже если ты знаешь об этой механике, тебе нужно предугадывать размер полотна или делать его сильно большим.

2022-11-08 13:50 UTC, Gorbacheb commented on cs/TagsCloudVisualizationTests/CircularCloudLayouterTests.cs
> +                    closerRectangle.X += Math.Sign(Center.X - rectangle.Center().X);
Проверяется не на пересечение с исходным, а на пересечение со всеми уже сгенерированными. Я генерирую новый прямоугольник, пытаюсь сместить его к центру, если он не пересекается с другими, значит прямоугольники стоят неплотно и фейл.

2022-11-08 15:15 UTC, Gorbacheb commented on cs/TagsCloudVisualization/Structures/QuadTreeNode.cs
> +                    return true;
Написал так из соображений производительности, если заменить, например, на Any будет работать в 10 раз дольше чем форик для 1e5 прямоугольников. Могу не знать в каких ситуациях насколько это критично, но, например, Unity не рекомендует использовать LINQ в целях производительности особенно в рекурсивных методах.

2022-11-08 16:27 UTC, Gorbacheb commented on cs/TagsCloudVisualizationTests/CircularCloudLayouterTests.cs
> +            rectangles.Clear();
До SetUp была нужна, потом забыл убрать

2022-11-08 16:28 UTC, Gorbacheb commented on cs/TagsCloudVisualizationTests/CircularCloudLayouterTests.cs
> +                    var res = closerRectangle.IntersectsWith(rectangles);
сокращение от result, привычки из спортивного программирования)

2022-11-11 07:40 UTC, Leoltron commented on cs/TagsCloudVisualization/Structures/QuadTreeNode.cs
> +                    return true;
Ты прав, LINQ действительно замедляет, но его преимущество - читаемость. Если замедление ощутимое (можешь сам попробовать на 1e5 прямоугольниках или даже тест производительности сделать), можешь оставить foreach.

2022-11-11 07:55 UTC, Leoltron commented on cs/TagsCloudVisualization/Structures/QuadTreeNode.cs
> +                    return true;
Но помни, что в последствии ты туда запихаешь прямоугольники для облака тегов, и там их много не будет.

2022-11-11 08:40 UTC, Leoltron commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        public CircularCloudLayouter(Size canvasSize)
Не совсем то, о чем я говорил. Во-первых, по задаче конструктор должен принимать центр пространства. Во-вторых, Layouter не знает заранее размер прямоугольников, которые в него будут кидать и пространство, в общем, неограничено.

2022-11-11 10:21 UTC, Leoltron commented on cs/TagsCloudVisualizationTests/CircularCloudLayouterTests.cs
> +                    closerRectangle.X += Math.Sign(Center.X - rectangle.Center().X);
Это не совсем о плотности, неплотная спираль, сделанная из квадратов, пройдет этот тест, но она не будет плотной. Есть другой способ проверять плотность облака, например, используя площади.

2022-11-11 15:41 UTC, Gorbacheb commented on cs/TagsCloudVisualizationTests/CircularCloudLayouterTests.cs
> +                    closerRectangle.X += Math.Sign(Center.X - rectangle.Center().X);
Я думал о площади, но мне этот вариант не понравился, так как сильно зависит от минимального и максимального размера генерируемых прямоугольников.
Согласен, что тут не совсем плотность проверяется, а отсутствие разреженности по вектору из центра прямоугольника к центру спирали, что по сути необходимое условие для плотности.
Квадраты проходят этот тест, если расположены крестом (+), да и не только квадраты, но и просто прямоугольники, если их центр попадает на ось абсцисс/ординат, но в условиях генерации по спирали такое не проходит. Для примера убрал TryShiftCenter и генерировал квадраты - не прошло.
Мне кажется лучше оставить этот тест и написать еще один на площади.

2022-11-14 08:29 UTC, Leoltron reviewed
Рисование в тестах сломалось, облако убежало в угол https://imgur.com/a/7gApHFD

2022-11-14 08:29 UTC, Leoltron commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            quadTreeCenter = new Point(MaxCanvasSize.Width / 2 + center.X, MaxCanvasSize.Height / 2 - center.Y);
Несколько вещей, которые я не понимаю:
1. Из того что я видел, центр квадродерева в `(MaxCanvasSize.Width / 2, MaxCanvasSize.Height / 2)`, почему он смещен здесь?
2. Почему по Y смещение в другую сторону?
3. Центр облака - это фактически и центр изображения. По идее, тебе не надо их разделять.

2022-11-14 09:09 UTC, Gorbacheb commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            quadTreeCenter = new Point(MaxCanvasSize.Width / 2 + center.X, MaxCanvasSize.Height / 2 - center.Y);
1. координаты считаются от левого верхнего угла, а на вход идут координаты в обычной декартовой системе, эта формула как раз преобразует из одного в другое.
2. Отличается направление оси Oy (из середины вверх -> от левого верхнего вниз ), направление Ox совпадает.
3. почему центр облака - это центр изображения? Облако будет в центре, если задали позицию (0,0), в остальных случаях оно будет смещено относительно центра на данных вектор, а максимальный размер дерева квадрантов будет обрезан и сгенерировано изображение.

2022-11-14 09:11 UTC, Gorbacheb commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            quadTreeCenter = new Point(MaxCanvasSize.Width / 2 + center.X, MaxCanvasSize.Height / 2 - center.Y);
Про рисование в тестах вообще забыл (

2022-11-14 09:51 UTC, Leoltron commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            quadTreeCenter = new Point(MaxCanvasSize.Width / 2 + center.X, MaxCanvasSize.Height / 2 - center.Y);
1. Странное предположение, Point в конструкторе работает по той же системе координат что и все остальное. Логика "больше Y - ниже идем" работает только когда мы рисуем что-то на экране.
3. Потому что ты так его рисуешь? И я не вижу никакой выгоды от разделения. С другой стороны, если центры совпадают, то квадродерево вмещает больше прямоугольников.

2022-11-14 09:59 UTC, Leoltron commented
У меня остались вопросы к реализации, но требования задачи выполнены, ставлю 3 балла.

2022-11-14 09:59 UTC, closed without merging