Вашурин Артем
kontur-csharper/tdd pull request #174
Opened 2022-11-07 06:54 UTC by ArtAkaArt

@daniilmardanov

2022-11-07 19:40 UTC, Danko19 requested changes

2022-11-07 19:40 UTC, Danko19 commented on cs/CircularCloudLayoutTests/CircularCloudLayoutTests.cs
> +        public void PlacedRectangles_Should_Fill_80Precent_OfCircleSpace()
Опечатка в слове Percent

2022-11-07 19:40 UTC, Danko19 commented on cs/CircularCloudLayoutTests/CircularCloudLayoutTests.cs
> +            for (int i = 0; i < placedRectanglesOutput.Count - 2; i++)
Кажется, при такой индексации мы пропускаем последнюю пару прямоугольников и не проверяем их на пересечение с другими

2022-11-07 19:40 UTC, Danko19 commented on cs/CircularCloudLayoutTests/CircularCloudLayoutTests.cs
> +            foreach (var rectangle in placedRectanglesOutput)
Не знаю, проходили ли вы, но этот foreach можно элегантно заменить на методы LINQ Min и Max

2022-11-07 19:40 UTC, Danko19 commented on cs/CircularCloudLayoutTests/CircularCloudLayoutTests.cs
> +            placedRectanglesOutput.Should().BeEquivalentTo(layout.PlacedRectangles);
Кажется, совсем необязательно делать PlacedRectangles публичным и проверять его. Нас в первую очередь интересует результат работы класса, а не его внутреннее состояние. Корректность его работы мы можем проверить как раз по возвращаемым результатам

2022-11-07 19:40 UTC, Danko19 commented on cs/CircularCloudLayoutTests/CircularCloudLayoutTests.cs
> +        public void PutNextRectangle_GiveSizeWhithNonpositiveDimensions_Should_ThrowArgumentException(int length,
Количество TestCase-ов можно сократить, ограничившись лишь несколькими граничными сценариями с 0 и -1

2022-11-07 19:40 UTC, Danko19 commented on cs/CircularCloudLayoutTests/CircularCloudLayoutTests.cs
> +                var x1 = rectangle.X - center.X;
Предлагаю для единообразия использовать `rectangle.Left` и `.Top` вместо `.X` и `.Y`

2022-11-07 19:40 UTC, Danko19 commented on cs/TagsCloudVisualization/SizeListBulder.cs
> +            return list;
Можно для интереса перемешать прямоугольники в произвольном порядке

2022-11-07 19:40 UTC, Danko19 commented on cs/CircularCloudLayoutTests/Usings.cs
> +global using NUnit.Framework;
Обычно так не делают, а просто подключают все необходимые юзинги в каждом файле. Тем более, за нас это делает rider 😉

2022-11-07 19:40 UTC, Danko19 commented on cs/TagsCloudVisualization/Program.cs
> +using static TagsCloudVisualization.SizeListBulder;
Лучше использовать явный вызов статического метода, а то мне несколько секунд пришлось искать, откуда же взялся этот `GetCustomSizes()` 😁
Статические юзинги уместны в случае, когда методы одного и того же класса вызываются в файле по многу раз, а само название класса длинное, чтобы сократить кол-во повторяющегося кода

2022-11-07 19:40 UTC, Danko19 commented on cs/TagsCloudVisualization/CircularCloudLayout.cs
> +        private Size currentSize;
Кажется, от полей `currentSize`  и `bufferedRectangle` можно избавиться, заменив их на локальные переменные и параметры методов.

Нужно стремиться к тому, чтобы по минимум использовать приватные не-readonly поля. Такой код сложнее читать, потому что приходится постоянно возвращаться к объявлению этого поля. Кроме того, нет гарантии, что в будущем кто-то другой не захочет написать новый метод, который тоже начнёт менять эти поля и сломает нашу текущую логику. 

Локальные переменные лучше тем, что полностью изолируют контекст отдельного метода. В полях же (глобальные переменные) допустимо хранить состояние класса, у нас это `pointer` и `PlacedRectangles`

2022-11-07 19:40 UTC, Danko19 commented on cs/TagsCloudVisualization/CircularCloudLayout.cs
> +        private bool RectangleIntesects(Rectangle rectangle) => PlacedRectangles.Any(x => x.IntersectsWith(rectangle));
Очепятка :D (в названии метода)

2022-11-08 07:54 UTC, ArtAkaArt commented on cs/TagsCloudVisualization/SizeListBulder.cs
> +            return list;
Добавил картинку в Readme =) Нарисована на версии этого [коммита](https://github.com/kontur-courses/tdd/pull/174/commits/523d0fc6a10e69ccdb483db23c888293452474e2)

2022-11-08 15:42 UTC, Danko19 commented on cs/TagsCloudVisualization/SizeListBulder.cs
> +            return list;
Отлично получилось!

2023-11-23 04:55 UTC, closed without merging