Сабреков Максим
kontur-csharper/tdd pull request #177
Opened 2022-11-07 12:50 UTC by IuxMorti

@desolver

2022-11-08 16:07 UTC, desolver requested changes

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/TagsCloudVisualization.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
Файл проекта в очень старом формате, а как ты создавал проект?
Можно на Net Core его создавать, не обязательно на стареньком net48

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/DrawerCloudLayouterForTests.cs
> +            var result = rectangles.Select(r => new ColoredRectangle(new Pen(Color.Blue), r)).ToList();
Для таких случаев "временного маппинга" лучше использовать анонимные объекты или кортежи. Представь, что у тебя в одном методе 10 `.Select(...)`, а 10 классов только ради одного метода создавать не хочется)
А `ColoredRectangle` можно будет удалить

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/CircularCloudLayouterShould.cs
> +    [TestFixture]
`[TestFixture]` можно не писать, дотнет и так будет считать этот класс классом для тестирования, если увидит внутри хоть один `[Test]`

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/CircularCloudLayouterShould.cs
> +    public class CircularCloudLayouterShould
Получилось смешение подходов к именованию тестов, в названии класса ты пишешь `...Should`, а в названиях методов не продолжаешь это предложение. Давай остановимся на чем-то одном. Предлагаю `Should` унести в названия тестов и формировать именование в этом стиле

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/CircularCloudLayouterShould.cs
> +        public void Test_CircularCloudLayouter_FirstRectangleInCenter()
Как уже писал выше над названиями нужно поработать:

- Не нужно писать `Test...`, ведь и так понятно, что это он)
- `CircularCloudLayouter` уже написан в названии класса, поэтому писать в названии методов его не нужно, возникает дублирование
- Преобразовать в название с `_Should...`
- Параметры методов вылезают за рамки экрана. Даже на fullhd монике приходится пользоваться горизонтальным скроллом. Если аргументов слишком много, лучше разносить их построчно

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/CircularCloudLayouterShould.cs
> +            r.Size.Should().Be(sizeRectangle);
В названии теста ты пишешь, что проверяешь центр вставленного прямоугольника, но при этом проверяешь ещё и его размер. Получается неочевидная логика, которую лучше разнести на два теста с понятными названиями

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/CircularCloudLayouterShould.cs
> +            var random = new Random();
Рандом в тестах не очень любят, т.к. он вносит долю неопределенности, чего в тестах быть не должно, т..к. тесты это контракт, а так представь такой тест упадет, а ты даже знать не будешь, на каком значении он упал. Такие ситуации лучше через `TestCase` разруливать, где ты сам явно скажешь, какие размеры хочешь проверить, и 100 раз тест не придется прогонять)

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/CircularCloudLayouterShould.cs
> +            AreThereAnyIntersectionsBetweenRectangles(rectangles.ToArray()).Should().BeFalse();
`...BetweenRectangles` не несет особого смысла, мы ведь и так можем передать в метод только `rectangles`

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/CircularCloudLayouterShould.cs
> +            var random = new Random();
Та же ситуация про рандом, ты уже проверил плотность в тесте выше, не зачем проверять её ещё раз, но на рандомных значениях размера

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/CircularCloudLayouterShould.cs
> +            bitMap.Save(path);
Круто, что получилось сделать сохранение в файлик 👍

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/DrawerCloudLayouterForTests.cs
> +            var colorRectangles = GetColorRectangles(rectangles);
Понимаю, что это тест, который на логику и скорость выполнения основного кода никак не повлияет, но ты пробегаешься по всем прямоугольникам (а их могут быть тысячи и больше) 4 раза за весь метод. Давай попробуем пооптимизировать?

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/DrawerCloudLayouterForTests.cs
> +    public class DrawerCloudLayouterForTests : DrawerCloudLayouter
Наследование в таком виде тут совсем не нужно, ты ведь не используешь никакую логику из базового класса, а полностью его переопределаешь. Лучше выделить интерфейс, от которого можно наследовать всех "рисовальщиков"

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/DrawerCloudLayouter.cs
> +    public class DrawerCloudLayouter
По конвентам существительное, отражающее главное действие класса, находится в конце названия. А тут получается, что у тебя класс - это лейаутер нарисованного облака, а не рисователь размещенного облака)

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/Spiral.cs
> +        private Point GetPointArchimedeanSpiral(float angle)
Сейчас метод говорит, что ты получаешь "архимедову спираль точки". Подумай над порядком элементов в названии метода

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/Spiral.cs
> +            while (true)
А если этот метод вызовется несколько миллионов (или миллиардов) раз, как думаешь, что тут произойдет?

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/Spiral.cs
> +            this.k = k;
- k - магическая буква)) понятно, что это некая переменная для вычислений, но нужно дать ей более понятное название
- А если stepAngle или k придут как 0, ожидается ли такое поведение?

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/Spiral.cs
> +                var countCircle = (int)(stepAngle / (Math.PI));
- Если это подразумевалось как "количество кругов", то снова перепутан порядок элементов в названии, сейчас получилось "круги количества"

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/CircularCloudLayouter.cs
> +                    location.Y - rectangleSize.Height / 2);
В решении приложены картинки с прямоугольниками примерно похожими на квадраты, приложи ещё, пожалуйста, совсем разнобойные прямоугольники, вытянутые в одну или другую сторону (но в рамках небольших размеров конечно)

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/CircularCloudLayouter.cs
> +            spiral = new Spiral(1/(float)( 2 * Math.PI), center);
Задачка на улучшение: если захочется генерировать точки не по спирали, а, например, волной, придется лезть в этот конструктор и руками менять тут реализацию, можно ли написать такой код, который будет позволять удобно задавать генератор точек не влезая в реализацию класса `CircularCloudLayouter` (возможно немного нужно будет отойти от интерфейса, предложенного в задаче)

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/CircularCloudLayouter.cs
> +        public Rectangle[] Rectangles => rectangles.ToArray();
Точно ли нужно это свойство?

2022-11-08 16:07 UTC, desolver commented on cs/CircularCloudLayouter/Program.cs
> +    public class Program
Общие комментарии по коду:

- Не забывай о форматировании файликов, внешний вид кода тоже важен, пройдись по ним автоформатированием. Где-то есть лишние отступы в виде пустых строк и отсутствия пробелов и неиспользуемые юзинги в файлах
- Проект с тестами и непосредственно реализацией лучше разделять на 2 отдельных проекта, так тесты не нагружают основной проект при сборке и не лезут со своим зависимостями. Давай и тут сделаем так же
- За творческую идею сделать через формочку однозначно лайк 👍 Но не забывай про сохранение в файл по завершению генерации (не в тестах, а именно в основной программе). Если не хочешь разбираться с формочкой, можешь убрать её и сделать просто через битмапу, я не против

2022-11-13 09:47 UTC, desolver requested changes

2022-11-13 09:47 UTC, desolver commented on cs/CircularCloudLayouter/CloudLayouterForm.cs
> +                    Directory.CreateDirectory("result");
`Directory.CreateDirectory(...)` ничего не сделает, если директория существует, поэтому if можно спокойно убрать

2022-11-13 09:47 UTC, desolver commented on cs/CircularCloudLayouter/CloudLayouterDrawer/ICloudLayouterDrawer.cs
> +        CloudLayouter CloudLayouter { get; }
В интерфейсе объекта, который должен просто что-то отрисовать, это кажется лишним

2022-11-13 09:47 UTC, desolver commented on cs/CircularCloudLayouter/CloudLayouterForm.cs
> +            Invalidate();
Из-за привязки к формам конечно много костыликов пришлось добавить, нехорошо. Код стал грязновато выглядеть с появлением метода `ChangeCenterPoint`, создав его, мы разрушили целостность класса, теперь в любой момент можно поменять центр спирали (непонятно зачем опять же, потому что лейаутер то один). Я думаю, ты сам когда писал заметил, что из-за него пришлось внести изменения в кучу мест, а поддерживать это ещё сложнее. Пусть лучше окно ресайзить нельзя будет, но код будет сильно чище. Давай лучше его удалим

2022-11-13 09:47 UTC, desolver commented on cs/CircularCloudLayouter/CloudLayouterForm.cs
> +                    .PutNextRectangle(new Size(random.Next(30, 30), random.Next(30, 100)));
Так делать нельзя) Drawer на то и рисовальщик, что просто рисует фигуры, он не должен вызывать никакие методы лейаутера через себя, рушится принцип единой ответственности (SRP)

2022-11-13 09:47 UTC, desolver commented on cs/CircularCloudLayouter/Curve/Spiral.cs
> +        }
Приватные методы должны располагаться ниже публичных. `public` -> `protected` -> `private`

2022-11-13 09:47 UTC, desolver commented on cs/CircularCloudLayouter/Curve/Spiral.cs
> +        }
Такие методы делать очень нежелательно, потому что в любой момент можно что-то сломать, вызывав его и не откатив центр обратно, выше уже писал почему, давай удалим его

2022-11-13 09:47 UTC, desolver commented on cs/CircularCloudLayouter/TagsCloudVisualization.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
По-прежнему проект в старом формате

2022-11-13 09:47 UTC, desolver commented on cs/TagCloudVisualizationTests/CloudLayouterShould.cs
> +        public static bool AreThereAnyIntersections(Rectangle[] rectangles)
Почему он публичный? Используется ведь только в этом файле

2022-11-13 09:47 UTC, desolver commented on cs/TagCloudVisualizationTests/Program.cs
> +    }
Проекту с тестами не нужен класс Program

2022-11-13 09:47 UTC, desolver commented on cs/TagCloudVisualizationTests/Properties/AssemblyInfo.cs
> +﻿using System.Reflection;
Нужно перейти на net core и удалить всё это

2022-11-13 09:47 UTC, desolver commented on cs/TagCloudVisualizationTests/TagCloudVisualizationTests.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
Проект создан на net48, это старая платформа, новые проекты уже можно создавать на последних фреймворках

2022-11-13 10:01 UTC, IuxMorti commented on cs/CircularCloudLayouter/Curve/Spiral.cs
> +        }
я обычно привык наоборот делать private-protected-public

2023-11-23 04:55 UTC, closed without merging