Соцук Виктор
kontur-csharper/tdd pull request #179
Opened 2022-11-07 14:30 UTC by viksot

@HELLoWorlD01100

2022-11-07 17:47 UTC, HELLoWorlD01100 reviewed
В целом круто.

По именованию тестов: 
Сейчас если у тебя в тесты добавляется какой-то новый метод, тебе придётся менять названия предыдущих тестов, чтобы понимать где какой метод тестируется.
Я предпочитаю использовать паттерн MethodName_Should*_When*
Потому что 
1) из имени теста понятны предмет тестирования, условия и результат.
2) имя теста читается как связное предложение.
Например: PutNextRectangle_ShouldThrowArgumentException_WhenNegativeWidth

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/ArchimedeanSpiral.cs
> +    public class ArchimedeanSpiral
Добавить Archimedean в расшаренный(!) словарь, чтобы не подчеркивало

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/ArchimedeanSpiral.cs
> +        public readonly Point _centralPoint;
Нарушение именования публичных полей.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/ArchimedeanSpiral.cs
> +        public double Parameter { get; set; }
Зачем тут свойства? Да еще и публичные.

Все обращения происходят внутри класса, инициализация только в конструкторе.

Чем это плохо? Возможно поменять извне эти параметры и всё сломается.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/ArchimedeanSpiral.cs
> +            Point nextPoint = new Point((int)(_centralPoint.X + Parameter * Angle * Math.Cos(Angle)),
var

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/ArchimedeanSpiral.cs
> +            Point nextPoint = new Point((int)(_centralPoint.X + Parameter * Angle * Math.Cos(Angle)),
Очень сложно читать, какие-то синусы, косинусы, еще и явно приведение типов.

Мб разделим на 
var x = ?
var y = ?
var nextPoint = ?

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/ArchimedeanSpiral.cs
> +            Angle += _deltaAngle;
Метод, судя по названию, занимается выдачей конкретной точки, почему он выполняет какую-то работу на будущее для следующей точки?

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/ArchimedeanSpiral.cs
> +        private readonly double _deltaAngle = 2 * Math.PI / 360;
Константа.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +        public List<Rectangle> Rectangles { get; }
![image](https://user-images.githubusercontent.com/54909098/200345636-dda66d26-2cb1-44fe-a336-7e19fa48b936.png)
Гляди как можно сделать. И всё опять сломается.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +        public List<Rectangle> Rectangles { get; }
Если хочешь показывать какие у тебя прямоугольники сейчас в алгоритме наружу, используй IReadOnlyList<T>. Как при этом будут добавляться элементы внутри CircularCloudLayouter - хочу, чтобы ты сам дошёл.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +        public Point CloudCenter { get; }
Не очень понятно зачем знать об этом. Учитывая, что мы и так знаем, т.к в конструктор передаем

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            Rectangles = new List<Rectangle>();
Я дефолтные значения, которые не требуют аргументов из конструктора, обычно выношу прям в свойство/поле, чтобы не засорять конструктор.

На твоё усмотрение.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +                rectangle = new Rectangle(new Point(point.X - rectangleSize.Width / 2, point.Y - rectangleSize.Height / 2), rectangleSize);
Лучше не затаскивать какую-то логику в конструктор, сложно разбирать всё это.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            VerifyRectangleSize(rectangleSize);
Лучше сделать метод IsValidRectangleSize, а сами исключения кидать здесь. Чтобы не приходилось ползать по коду туда сюда.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            return Rectangles?.Any(r => r.IntersectsWith(rectangle)) ?? false;
Подумай как можно упростить. Сейчас приходится думать какие тут ситуации возможны, хотя простой код, который может вернуть true или false.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            return axleDistances[0] == 0 && axleDistances[1] == 0;
В массиве всегда будет два элемента. Это точно та структура данных, которая здесь подходит?

Чтобы понять всю логику, приходится лезть глубже(а что такое axleDistances[0]?, почему должно быть равно 0 и тд) , хотя этого можно избежать.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            return new int[] { pointA.X - pointB.X, pointA.Y - pointB.Y };
int[] можно убрать

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +        private Vector[] GetShiftAxialOrts(Rectangle rectangle)
Orts - это? У меня не переводится. :)

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +        private int[] GetAxialDistancesBetweenPoints(Point pointA, Point pointB)
А как так вышло, что дистанция может быть отрицательным значением?

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +                    if (axleDistances[i] == 0)
Слабый контракт. Нигде не зафиксировано, что множества изоморфны.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            if (IsIntersectWithAnyRectangle(movedRectangle))
Можно сократить.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +                this.PutNextRectangle(size);
Зачем тут this?

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +        public void PutRectangles(List<Size> sizes)
Теперь интерфейс выглядит так:

class CircularCloudLayouter
{
  CircularCloudLayouter(Point center)
  Rectangle PutNextRectangle(Size rectangleSize)
  void PutRectangles(List<Size> sizes)
}

+ непонятно зачем нужен публичный метод PutNextRectangle.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +        public Rectangle PutNextRectangle(Size rectangleSize)
Не используется возвращаемое значение. 

Кажется, по логике задания, нужно возвращать тот прямоугольник, который подходит, а не складывать внутри в коллекцию, чтобы потом когда-то получить.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +        public void PutRectangles(List<Size> sizes)
Метод в принципе странно выглядит: почему не возвращать сразу же коллекцию прямоугольников, вместо того, чтобы складывать их куда-то получать через свойство.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +        private const int minFontSize = 6;
Почему именно такие значения?

Хорошей практикой было бы вынести их в настройки приложения, но на данном этапе обучения можно забить.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +        public Size Size { get; set; }
get-only

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +    public class CloudImageHandler
Handler - довольно общее название. А из название читается, что этот класс обрабатывает какие то облачные изображения/изображения с облаками.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +        public Bitmap Bitmap { get; private set; }
Почему тут решил использовать private set, а выше обычный set?

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +    public class CloudImageHandler
Какие проблемы вижу в текущей реализации CloudImageHandler
1. Если появится Layouter, который раскладывает облако в квадрат, то надо будет писать под него отдельный CloudImageHandler? 
2. Если мне нужно генерить картинки одинакового размера, мне каждый раз придётся создавать новый объект, хотя поменялся только набор прямоугольников. Это доставит проблем при внедрении зависимостей. 
Вы это будете проходить попозже, но можешь сейчас почитать про это, ничего сложного там нету. В данный момент можно просто поверить, что возникнет какая-то проблема :)
3. Представим, что у нас теперь не локальное приложение, а апишка. И нас просят сгенерировать такое изображение. Какие видишь тут проблемы?

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +            graphics.FillRectangle(Brushes.AliceBlue, 0, 0, bitmap.Width, bitmap.Height);
По-моему ты в одном месте приводил координаты к центру прямоугольника, а теперь это просто верхняя левая точка.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +            graphics.FillRectangle(Brushes.AliceBlue, 0, 0, bitmap.Width, bitmap.Height);
Если захочу поменять цвет, придётся искать где такое происходит рисование. Мб выделим нашу палитру в поля?

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +                graphics.DrawRectangle(new Pen(Color.Black, 1), rectangle);
Точно надо каждый раз создавать Pen?

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +            var stringFormat = new StringFormat();
Заиспользуй {Alignment = , LineAlignment =}, так же короче и понятнее.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +            for (int i = 0; i < Layouter.Rectangles.Count; i++)
foreach

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +                    new Font("Arial", GetFontSize(Layouter.Rectangles[i])),
Arial можно вынести в константу

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +            int fontSize = minFontSize + (maxFontSize - minFontSize) * (square - minRectangleSquare) /
Откуда такая формула взялась?

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/Program.cs
> +            if (solutionDirectory.GetDirectories("TagCloudImages").Any())
DRY

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/Vector.cs
> +    public class Vector
Какое принципиальное отличие от Point?

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/Vector.cs
> +        public Vector GetOppositeVector()
не используется

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +    public class ArchimedeanSpiral_Should
Достаточно странное название для класса. Лучше назвать ArchimedeanSpiralTests

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloud/ArchimedeanSpiral.cs
> +        public double Parameter { get; set; }
Parameter - достаточно общее название. Можем конкретизировать?

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +        }
DRY

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +            _archimedeanSpiral = new ArchimedeanSpiral(new Point(0, 0));
А всегда ли начальная точка должна быть 0;0?

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +        public void ReturnsCorrectPoint_WhenAngleEqualsHalfPi()
Я бы взял еще PI/4.
Другие табличные бы не брал, потому что возможны различия из-за корней, нам это не так интересно.

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +        public void ReturnsCorrectPoint_WhenAngleEqualsHalfPi()
Также не вижу тестов, где parameter != 1

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouter_Should.cs
> +            _layouter.PutNextRectangle(new Size(10, 10));
- Квадрат - лишь частный случай прямоугольника. Почему тестируем только на квадрате?

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouter_Should.cs
> +            _layouter.Rectangles.Count.Should().Be(0);
А по контракту, который ты задал, это не обязательно :)

2022-11-07 17:47 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouter_Should.cs
> +            action.Should().Throw<ArgumentException>().WithMessage("width and height of rectangle must be more than zero");
А если я сообщение поменяю, у меня сразу тесты начнут падать, хотя функционал работает... 
Почему решил, что эта проверка тут нужна в принципе?

2022-11-08 16:11 UTC, viksot commented on cs/TagCloud/ArchimedeanSpiral.cs
> +    public class ArchimedeanSpiral
\+

2022-11-08 16:30 UTC, viksot commented on cs/TagCloud/ArchimedeanSpiral.cs
> +        public readonly Point _centralPoint;
\+

2022-11-08 16:38 UTC, viksot commented on cs/TagCloud/ArchimedeanSpiral.cs
> +        public double Parameter { get; set; }
\+

2022-11-08 16:42 UTC, viksot commented on cs/TagCloud/ArchimedeanSpiral.cs
> +        public double Parameter { get; set; }
\+

2022-11-08 16:44 UTC, viksot commented on cs/TagCloud/ArchimedeanSpiral.cs
> +        private readonly double _deltaAngle = 2 * Math.PI / 360;
\+

2022-11-08 16:50 UTC, viksot commented on cs/TagCloud/ArchimedeanSpiral.cs
> +            Point nextPoint = new Point((int)(_centralPoint.X + Parameter * Angle * Math.Cos(Angle)),
\+

2022-11-08 16:55 UTC, viksot commented on cs/TagCloud/ArchimedeanSpiral.cs
> +            Point nextPoint = new Point((int)(_centralPoint.X + Parameter * Angle * Math.Cos(Angle)),
\+

2022-11-08 17:22 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +        public Point CloudCenter { get; }
Может быть ситуация, что при передаче в метод экземпляра CircularCloudLayouter, в этом методе потребуется информация о центре облака. Это легко сделать при наличии соответствующего поля. Например, в этом тесте мне нужно получить центр облака для проверки выравнивания прямоугольников. А конструктор CircularCloudLayouter() и информация о центре облака были в методе Setup()

![Test](https://user-images.githubusercontent.com/106755507/200631330-111e8835-0865-4772-9393-9ccb254fb441.png)

С другой стороны, в тестах можно сделать своё поле CloudCenter. Тогда в классе CircularCloudLayouter поле CloudCenter сделать private readonly

2022-11-08 18:03 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +        public List<Rectangle> Rectangles { get; }
\+

2022-11-08 18:05 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            Rectangles = new List<Rectangle>();
\+

При таком подходе код выглядит аккуратнее

2022-11-08 18:12 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            VerifyRectangleSize(rectangleSize);
\+

2022-11-08 18:13 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +                rectangle = new Rectangle(new Point(point.X - rectangleSize.Width / 2, point.Y - rectangleSize.Height / 2), rectangleSize);
\+

2022-11-08 18:17 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            return Rectangles?.Any(r => r.IntersectsWith(rectangle)) ?? false;
\+

2022-11-08 21:50 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +        private int[] GetAxialDistancesBetweenPoints(Point pointA, Point pointB)
\+

Некорректное название. Переработал логику

2022-11-08 21:52 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            return new int[] { pointA.X - pointB.X, pointA.Y - pointB.Y };
\+

2022-11-08 21:53 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            return axleDistances[0] == 0 && axleDistances[1] == 0;
\+

Переработал логику

2022-11-08 21:55 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +        private Vector[] GetShiftAxialOrts(Rectangle rectangle)
\+
Это орт - единичный вектор вдоль оси. В зависимости от знака задаёт направление сдвига вдоль своей оси.
Убрал этот метод.

2022-11-08 21:57 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            if (IsIntersectWithAnyRectangle(movedRectangle))
\+
Убрал этот метод.

2022-11-08 21:58 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +                this.PutNextRectangle(size);
\+

2022-11-09 09:20 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +    public class CloudImageHandler
1. В таком случае CloudImageHandler переписывать не надо будет. CloudImageHandler берёт из CircularCloudLayouter только коллекцию IReadOnlyList<Rectangle>. По какому алгоритму раскладка получена CloudImageHandler не интересует. Также в самом названии класса CloudImageHandler отсутствует отсылка на форму облака.

2022-11-09 11:50 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +    public class CloudImageHandler
2. Преобразовал класс, чтобы интерфейс выглядел таким образом:

public class CloudImage
{
public CloudImage(Size size)
public Bitmap CreateFrom(CircularCloudLayouter layouter)
}

2022-11-09 12:24 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +    public class CloudImageHandler
3. Если честно, не очень разбираюсь в API. Но с новым интерфейсом явных проблем с использованием в API не будет. А в старой версии, думаю, лишним был метод  public void SaveImage(string fullFilePath) - подразумевается только сохранение на локальный диск

2022-11-09 12:27 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +        private const int minFontSize = 6;
Получены эмпирическим путём. Это для экспериментов для дальнейшего развития задачи, когда надо будет слова вместо прямоугольников рисовать

2022-11-09 12:28 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +        public Size Size { get; set; }
\+
Сделал 
public readonly Size ImageSize;

2022-11-09 12:29 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +        public Bitmap Bitmap { get; private set; }
\+ 
ошибка. В новой версии убрал эти свойства вообще

2022-11-09 12:32 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +            graphics.FillRectangle(Brushes.AliceBlue, 0, 0, bitmap.Width, bitmap.Height);
Так это просто закраска заднего фона

2022-11-09 12:44 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +            graphics.FillRectangle(Brushes.AliceBlue, 0, 0, bitmap.Width, bitmap.Height);
Выделил в свойства из предположения, что пользователь захочет палитру в процессе поменять

2022-11-09 12:45 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +                graphics.DrawRectangle(new Pen(Color.Black, 1), rectangle);
\+

2022-11-09 12:49 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +            var stringFormat = new StringFormat();
\+

2022-11-09 12:53 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +            for (int i = 0; i < Layouter.Rectangles.Count; i++)
Нужен индекс прямоугольника для генерации строки

![image](https://user-images.githubusercontent.com/106755507/200835487-a972233e-07b8-414b-8029-89030a811c7b.png)

2022-11-09 12:55 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +                    new Font("Arial", GetFontSize(Layouter.Rectangles[i])),
\+

2022-11-09 12:57 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +            int fontSize = minFontSize + (maxFontSize - minFontSize) * (square - minRectangleSquare) /
Линейная интерполяция. Максимальному по площади прямоугольнику максимальный шрифт, минимальному прямоугольнику - минимальный, а промежуточному прямоугольнику соответствующий промежуточный

2022-11-09 14:39 UTC, viksot commented on cs/TagCloud/Program.cs
> +            if (solutionDirectory.GetDirectories("TagCloudImages").Any())
\+

2022-11-09 14:47 UTC, viksot commented on cs/TagCloud/Vector.cs
> +    public class Vector
Вектор направленный отрезок прямой. Удобно использовать было для вычисления направлений перемещения прямоугольников, определения выравниваний. При работе с графикой, движением использование векторов мне показалось удобным.

2022-11-09 14:52 UTC, viksot commented on cs/TagCloud/Vector.cs
> +        public Vector GetOppositeVector()
\+

2022-11-09 14:59 UTC, viksot commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +    public class ArchimedeanSpiral_Should
На курсе в лекционном материале часто применялись названия тестовых классов по шаблону ClassUnderTest_Should. Например:

![image](https://user-images.githubusercontent.com/106755507/200863917-088a979b-8cfc-4026-99b1-7924995e7df8.png)

Переименовал на ArchimedeanSpiralTests

2022-11-09 15:02 UTC, viksot commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +            _archimedeanSpiral = new ArchimedeanSpiral(new Point(0, 0));
Точка может быть произвольной. Точка (0,0) выбрана для удобство тестирования. Чтобы можно было легко посчитать координаты точек спирали без учёта смещения центра

2022-11-09 19:43 UTC, viksot commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +        public void ReturnsCorrectPoint_WhenAngleEqualsHalfPi()
\+

2022-11-09 19:43 UTC, viksot commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +        public void ReturnsCorrectPoint_WhenAngleEqualsHalfPi()
\+

2022-11-09 19:43 UTC, viksot commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +        }
\+

2022-11-09 19:47 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouter_Should.cs
> +            _layouter.Rectangles.Count.Should().Be(0);
\+
Проблема решается за счёт IReadOnlyList<Rectangle>

2022-11-09 19:51 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouter_Should.cs
> +            _layouter.PutNextRectangle(new Size(10, 10));
Конкретно для этого теста вообще неважно форма. Тестируется количество добавленных прямоугольников в коллекцию

2022-11-09 19:55 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouter_Should.cs
> +            action.Should().Throw<ArgumentException>().WithMessage("width and height of rectangle must be more than zero");
Проверяется корректность выбрасывания исключения. Сообщение исключения это же его параметр. Если выброситься исключение с другим сообщением, тогда это не то исключение, что нужно - исключение некорректно.

2022-11-09 20:00 UTC, viksot commented on cs/TagCloud/ArchimedeanSpiral.cs
> +            Point nextPoint = new Point((int)(_centralPoint.X + Parameter * Angle * Math.Cos(Angle)),
а чем плоха явная типизация переменных? Сразу же понятно, что за тип переменной. Например, не нужно смотреть какой тип возвращаемого значения у метода. 

var для универсальности кода?

2022-11-10 18:50 UTC, HELLoWorlD01100 commented on cs/TagCloud/ArchimedeanSpiral.cs
> +            Point nextPoint = new Point((int)(_centralPoint.X + Parameter * Angle * Math.Cos(Angle)),
Я бы привел такие аргументы, чтобы использовать var: 
- Придётся более точно называть переменные. Чтобы не возникало мыслей "ну тут по типу понятно, что это точка, назову ее просто next". А потом придётся понимать что за next
- Убирается излишний код, который информативности не дает.
- Может быть неявное приведение типов.
- Писать var банально проще, чем думать о том, какой же тип мне тут нужно.
- Если типы не встроенные, то будут появляться using'и, опять же засорение кода, хоть и незначительное. 


> Сразу же понятно, что за тип переменной.
У тебя дальше идет код "new Point", этого недостаточно, чтобы тип понять?)

2022-11-10 18:56 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +        public Point CloudCenter { get; }
Менять основой код не стоит ради тестов. Если приходится менять код ради тестов, то скорее всего тесты написаны неправильно.
Бывают очень редкие исключения, у меня как раз такое было недавно, могу рассказать :))

В принципе в том, чтобы добавить какую-то мета-информацию наружу только для вычитывания, я не вижу ничего плохого(например, Length/Count, который достаточно часто используют).

2022-11-10 18:57 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +        private Vector[] GetShiftAxialOrts(Rectangle rectangle)
Я тут больше намекал на то, что ты используешь русские термины транслитом)

2022-11-10 19:06 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +    public class CloudImageHandler
1. Говоришь правильно, а код пишешь нет. У нас сейчас явно зафиксировано, что CloudImageHandler принимает в кач-ве Layouter только CircularCloudLayouter. 
2. Ок, когда будет второй круг ревью, посмотрю детальнее.
3. Про апи можем просто так поговорить. А проблему правильно увидел :)

2022-11-10 19:07 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageHandler.cs
> +            for (int i = 0; i < Layouter.Rectangles.Count; i++)
А это же ты чисто логику придумал. В задании, для которого ты это реализовывал, не нужно индекс в кач-ве текста использовать :))

2022-11-10 19:10 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +            _archimedeanSpiral = new ArchimedeanSpiral(new Point(0, 0));
А тесты правда должны проходить только при идеальных  для тебя условиях? 

Может тебе точку (1, 1) отправят в алгоритм и всё сломается. А ты об этом узнаешь, когда в прод выкатишь, т.к тесты у тебя не покрывают точки, отличные от 0, 0. Все точки, разумеется, проверять не нужно.

2022-11-10 19:11 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouter_Should.cs
> +            _layouter.PutNextRectangle(new Size(10, 10));
Рассматривай класс, который ты тестируешь, как черный ящик. 

Вдруг у нас прямоугольники не закидываются в коллекцию? И только квадраты туда попадают

2022-11-10 19:16 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +    public class ArchimedeanSpiral_Should
Интересно. Я такой подход к именованию не встречал. 

Под странным, я имею в виду то, что в названии класса есть глагол. + Нет смеси snake_case и camelCase.

Да и в принципе именование, которое я предложил, выглядит красивее, но оставляю тогда на твоё усмотрение, раз привёл аргументы, что такое допустимо использовать :)

2022-11-10 19:21 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouter_Should.cs
> +            action.Should().Throw<ArgumentException>().WithMessage("width and height of rectangle must be more than zero");
Ну то, что это уже не эквивалентно то исключение,- правда.

Только из-за такого подхода возможна ситуация, что у нас добавился функционал(например, проверяем еще что площадь должна быть меньше 10), мы изменили сообщение на "width and height of rectangle must be more than zero and square should be less than 10".
Из-за этого придётся разбираться почему там тесты начали падать из-за нового функционала. 

Ну а еще DRY, т.к мы одно и то же в двух местах написали и к тому же одно влияет на поведение другого.

2022-11-10 19:24 UTC, HELLoWorlD01100 commented on cs/TagCloud/Vector.cs
> +    public class Vector
Я имею в виду то, чем они как классы отличаются? Я вижу только то, что есть два метода новых, которые можно было сделать через методы расширения. А мы под это выделили новый класс.

2022-11-11 09:06 UTC, viksot commented on cs/TagCloud/ArchimedeanSpiral.cs
> +            Angle += _deltaAngle;
\+

2022-11-11 09:09 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +        public Point CloudCenter { get; }
Расскажи) для общего развития мне точно не помешает)

> Бывают очень редкие исключения, у меня как раз такое было недавно, могу рассказать :))

2022-11-11 09:09 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +                    if (axleDistances[i] == 0)
\+

2022-11-11 09:12 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +        private Vector[] GetShiftAxialOrts(Rectangle rectangle)
\+

А, я искренне верил, что по-английски так же будет

2022-11-11 09:19 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +        private const int minFontSize = 6;
Убрал функциональность по выводу текста, чтобы YAGNI не нарушать

2022-11-11 09:19 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +            for (int i = 0; i < Layouter.Rectangles.Count; i++)
Убрал функциональность по выводу текста, чтобы YAGNI не нарушать

2022-11-11 09:22 UTC, viksot commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +    public class ArchimedeanSpiral_Should
Я поменял, как ты предложил. Выглядит красивее, согласен

2022-11-11 09:51 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +        public void PutRectangles(List<Size> sizes)
\+ Убрал этот метод. Привёл интерфейс в соответствие

2022-11-11 11:39 UTC, viksot commented on cs/TagCloud/ArchimedeanSpiral.cs
> +            Point nextPoint = new Point((int)(_centralPoint.X + Parameter * Angle * Math.Cos(Angle)),
Понял, спасибо

2022-11-11 11:40 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +        public Rectangle PutNextRectangle(Size rectangleSize)
\+

2022-11-11 11:59 UTC, viksot commented on cs/TagCloud/CloudImageHandler.cs
> +    public class CloudImageHandler
1. и 2. Ещё раз обновил интерфейс

![image](https://user-images.githubusercontent.com/106755507/201335390-93a46d2f-5403-4838-8d60-56cea6890152.png)

Но явно не хватает класса TagCloud, который будет итоговую раскладку хранить.  Класс CloudImageGenerator сейчас выполняет 2 работы - создаёт раскладку прямоугольников и создаёт само изображение.

2022-11-11 12:32 UTC, viksot commented on cs/TagCloud/Vector.cs
> +    public class Vector
Отличаются тем, что у векторов есть специфическая функциональность, в частности перпендикулярность. Это я использую для проверки выровнен ли прямоугольник по отношению к центру в  методе IsRectangleAlignedAlongDirection(). 
Можно было бы аналог метода IsPerpendicularTo(Vector other) сделать в расширении класса Point. С сигнатурой IsRightAngle(Point pointA, Point pointB, Point pointC). В таком случае будет важен порядок аргументов - второй точкой должна идти вершина угла. Соответственно, есть большая вероятность ошибок.
Проработал варианты реализации IsRightAngle. Можно сделать сделать через скалярные произведения векторов между точками (но снова выходим на сущность векторов), либо по теореме Пифагора (не критичен порядок точек, но вычислений ещё больше).
Считаю, что проверка выравнивая прямоугольника через вектора более "физична", чем по точкам. Если выделение класса вектора критично, то уберу его, сделаю через класс Point

2022-11-11 13:09 UTC, viksot commented on cs/TagCloudUnitTests/ArchimedeanSpiral_Should.cs
> +            _archimedeanSpiral = new ArchimedeanSpiral(new Point(0, 0));
\+

2022-11-11 13:09 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouter_Should.cs
> +            _layouter.PutNextRectangle(new Size(10, 10));
\+

2022-11-11 13:20 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouter_Should.cs
> +            action.Should().Throw<ArgumentException>().WithMessage("width and height of rectangle must be more than zero");
Может я не понял проблему, но можно же в таком случае сделать следующее в конструкторе 

![image](https://user-images.githubusercontent.com/106755507/201348517-4eff0b1a-a464-4ead-8401-ed3b91680668.png)

И сделать соответствующий тест
![image](https://user-images.githubusercontent.com/106755507/201348456-988a632e-072a-4f83-ade7-3c3f136f39fb.png)

Получается, каждую логически отличающуюся проверка закрыли своим тестом.

2022-11-12 08:37 UTC, HELLoWorlD01100 reviewed
Еще вот такое будет, если прямоугольников будет слишком много 
![Equivalent_rectangles_cloud](https://user-images.githubusercontent.com/54909098/201466194-17edb737-b8ce-47d2-937d-c54120abc2d3.png)

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/ArchimedeanSpiral.cs
> +        public readonly Point CentralPoint;
Давай рассмотрим чем отличается get-only от readonly.
readonly - изменения только в конструкторе.
get-only - изменения только внутри класса.

Есть устоявшееся правило, что для публичных полей используем get-only, для приватных полей - readonly.

Хотя бы для того, чтобы если вдруг тебе понадобится изменять внутри класса в дальнейшем, было меньше правок.

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/ArchimedeanSpiral.cs
> +            var currentAngle = GetAngleAndUpdate();
Тут не какая-то сложная логика, чтобы выносить ее в отдельный метод. Но спагетти-код это плодит.

Выделять методы - круто, но переусердствовать с этим не нужно. Надо найти золотую середину :)

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            rectangle = ShiftRectangleToCenterPoint(rectangle);
Хорошей практикой было бы не класть в эту же переменную, а создать новую.
Тут стоит руководствоваться логикой, что мало ли как эту переменную изменят, а тебе нужна конкретно эта.

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            foreach (var direction in directionsToShift)
В райдере эта штука подсвечивается как возможная для оптимизации.
Вот так можно заменить: 
return directionsToShift.Aggregate(rectangle, ShiftRectangleAlongDirection);

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            foreach (var direction in directionsToShift)
Вообще в большинстве случаев стоит следовать совета ide

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            int deltaX = CloudCenter.X - rectangle.GetCenter().X > 0 ? 1 : -1;
var

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            return new[] { new Vector(deltaX, 0), new Vector(0, deltaY) };
Почему мы используем для этого массивы? В прошлом круге я оставлял по этому поводу комментарий. 
Посмотри в сторону [Tuple](https://learn.microsoft.com/ru-ru/dotnet/csharp/language-reference/builtin-types/value-tuples)

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            while (TryShiftRectangleAlongDirection(rectangle, direction, out Rectangle shiftedRectangle))
out var

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            if (IsIntersectWithAnyExistingRectangle(shiftedRectangle))
Можно сократить

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            var shiftedLocation = rectangle.Location.MoveOn(direction.X, direction.Y);
Уверен, что нам нужно знать о том, какое поле отвечает за расположение?
+ DRY

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            var vectorBetweenCenters = Vector.GetVectorBetweenPoints(CloudCenter, rectangle.GetCenter());
Можно сделать конструктор в Векторе, который принимает две точки.

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageGenerator.cs
> +        public readonly Size ImageSize;
why public

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageGenerator.cs
> +        public Color RectangleBorderColor { get; set; }
Зачем нам публичный сеттер? Зачем кому то знать о цвете извне?

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageGenerator.cs
> +        public Bitmap Generate(IReadOnlyList<Rectangle> layout)
IEnumerable<Rectangle> . 

Я более чем уверен, что будет downcast, если передавать обычный массив

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageGenerator.cs
> +        public Bitmap Generate(IReadOnlyList<Rectangle> layout)
Generate what? Из названия должно быть понятно что метод делает

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageGenerator.cs
> +        private Rectangle[] GetLayout(IReadOnlyList<Size> rectanglesSizes)
Можно написать в одну строку

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ArchimedeanSpiralTests.cs
> +        private static readonly object[] TestsParameters =
Выглядит как что-то страшное, неудобное для восприятия. Нет объяснения в названиях тестов что это, чисто параметры прописываются.

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ArchimedeanSpiralTests.cs
> +        public void GetNextPoint_ReturnsCorrectPoint_WhenSpiralTurnedOnAngle(Point centralPoint, double scaleFactor, double angleOnRadians, Point point)
point - ???

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +    internal class CircularCloudLayouterTests
Сейчас придётся искать папку где изображения сохранены, искать нужную папку, нужное изображение. Мб стоит писать путь к изображению после прохождения теста?

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +        private static DirectoryInfo GetSolutionDirectory()
Где то я такой код уже видел

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +        [TestCase(2, Category = "Layout")]
Выноси всякие строчки, которые повторяются, в константы. А то придётся потом каждую из них менять

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +    internal class CircularCloudLayouterTests
Запускаю тесты, а изображения не сохраняются.

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +    internal class CircularCloudLayouterTests
Мб выделить в отдельную сущность сохранения изображений? У нас сейчас расплывается эта логика

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageGenerator.cs
> +            var graphics = Graphics.FromImage(bitmap);
![image](https://user-images.githubusercontent.com/54909098/201465668-f21b5060-c554-470b-8686-33facc6dd0f3.png)

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +    internal class CircularCloudLayouterTests
Сейчас, если я правильно понимаю, старые результаты старых тестов затираются. А если мне нужно видеть результаты предыдущих тестов?

2022-11-12 08:37 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +        public void PutNextRectangle_ThrowsArgumentException_WhenSizeIsInvalid(int width, int height)
Что кстати будет, если мы попробуем нарисовать тут результаты?)

2022-11-12 20:51 UTC, viksot commented on cs/TagCloud/ArchimedeanSpiral.cs
> +        public readonly Point CentralPoint;
\+

Не знал. Исправил везде
> Есть устоявшееся правило, что для публичных полей используем get-only, для приватных полей - readonly.

2022-11-12 21:12 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            rectangle = ShiftRectangleToCenterPoint(rectangle);
\+

2022-11-12 21:25 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            foreach (var direction in directionsToShift)
\+

2022-11-12 21:26 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            int deltaX = CloudCenter.X - rectangle.GetCenter().X > 0 ? 1 : -1;
\+

2022-11-12 21:42 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            return new[] { new Vector(deltaX, 0), new Vector(0, deltaY) };
Пардон, забыл дать объяснение на первом круге. Использовал массив потому, что элементы представляют собой сущности одной природы. А кортежи, как я понял, для реализации набора переменных различных типов, не связанных между собой логически.

Попробовал сделать через кортеж. Стали красными методы, использующие LINQ, так как кортежи не реализуют IEnumerable:

![image](https://user-images.githubusercontent.com/106755507/201495447-7a2d523e-cdf4-4da4-b0aa-2340bfb40575.png)

IDE предлагает в качество возвращаемого значения метода вместо массива использовать IEnumerable<Vector>. Пока сделал так. Допустимо?

2022-11-12 21:43 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            return new[] { new Vector(deltaX, 0), new Vector(0, deltaY) };
\+

2022-11-12 21:44 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            while (TryShiftRectangleAlongDirection(rectangle, direction, out Rectangle shiftedRectangle))
\+

2022-11-12 21:44 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            if (IsIntersectWithAnyExistingRectangle(shiftedRectangle))
\+

2022-11-12 21:52 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            var shiftedLocation = rectangle.Location.MoveOn(direction.X, direction.Y);
1 . Грубо говоря, поле не нужно, да. Я его выделил, чтобы не засовывать сложную логику в конструктор прямоугольника

![image](https://user-images.githubusercontent.com/106755507/201495868-38af8d7f-115e-483c-9051-a7973049b381.png)

2. Не понял про DRY.

2022-11-13 08:23 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            var vectorBetweenCenters = Vector.GetVectorBetweenPoints(CloudCenter, rectangle.GetCenter());
\+

2022-11-13 08:37 UTC, viksot commented on cs/TagCloud/CloudImageGenerator.cs
> +        public readonly Size ImageSize;
\+

Делал поля класса CloudImageGenerator() открытыми, чтобы после создания экземпляра класса можно бы его перенастроить для рисования другого облака

2022-11-13 08:37 UTC, viksot commented on cs/TagCloud/CloudImageGenerator.cs
> +        public Color RectangleBorderColor { get; set; }
\+

Делал публичным, чтобы после создания экземпляра класса можно бы его перенастроить для рисования другого облака

2022-11-13 08:45 UTC, viksot commented on cs/TagCloud/CloudImageGenerator.cs
> +        public Bitmap Generate(IReadOnlyList<Rectangle> layout)
\+ 

То есть IReadOnlyList только для возвращаемых значений методов использовать?

2022-11-13 08:47 UTC, viksot commented on cs/TagCloud/CloudImageGenerator.cs
> +        public Bitmap Generate(IReadOnlyList<Rectangle> layout)
\+

2022-11-13 08:48 UTC, viksot commented on cs/TagCloud/CloudImageGenerator.cs
> +        private Rectangle[] GetLayout(IReadOnlyList<Size> rectanglesSizes)
\+

2022-11-13 10:27 UTC, viksot commented on cs/TagCloudUnitTests/ArchimedeanSpiralTests.cs
> +        private static readonly object[] TestsParameters =
\+

2022-11-13 10:31 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +    internal class CircularCloudLayouterTests
1. \+
2. Так нужно сохранять изображения, если тест падает. А тесты не падают. Для обратного эффекта нужно код ломать. А ДЗ с красными тестами не принимаются)
3. \+
4. \+

2022-11-13 13:21 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +        public void PutNextRectangle_ThrowsArgumentException_WhenSizeIsInvalid(int width, int height)
\+

Будет ошибка, так как рисовать нечего.
Но чтобы такого не было, отнёс тесты с отрисовкой раскладки к категории "Layout". И в методе TearDown() в случае падения теста отрисовываю раскладку только, если тест относится к категории "Layout". Но уже понял, что это небезопасно, так как можно ошибиться с внесем/невнесением теста в категорию "Layout". Переделал

2022-11-13 13:23 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +        [TestCase(2, Category = "Layout")]
\+

2022-11-13 13:23 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +        private static DirectoryInfo GetSolutionDirectory()
\+

2022-11-13 14:00 UTC, viksot commented on cs/TagCloud/ArchimedeanSpiral.cs
> +            var currentAngle = GetAngleAndUpdate();
/+

2022-11-13 14:14 UTC, viksot commented on cs/TagCloud/CloudImageGenerator.cs
> +            var graphics = Graphics.FromImage(bitmap);
Не понял

2022-11-14 10:59 UTC, viksot commented on cs/TagCloudUnitTests/ArchimedeanSpiralTests.cs
> +        public void GetNextPoint_ReturnsCorrectPoint_WhenSpiralTurnedOnAngle(Point centralPoint, double scaleFactor, double angleOnRadians, Point point)
\+

2022-11-14 18:42 UTC, HELLoWorlD01100 requested changes

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            return new[] { new Vector(deltaX, 0), new Vector(0, deltaY) };
![image](https://user-images.githubusercontent.com/54909098/201725637-8dad67f8-7658-45bd-8694-392b1717444b.png)

Главное отличие кортежа от массива - неизменяемость. И это свойство мы можем применить здесь. 

Я против использования массива здесь, потому что 1) есть возможность обращаться к несуществующему индексу, 2) нет понимания где какой сдвиг, придётся лезть в код.

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloud/CircularCloudLayouter.cs
> +            var shiftedLocation = rectangle.Location.MoveOn(direction.X, direction.Y);
Dry - тебе везде придётся писать rectangle.Location.MoveOn(...), а не rectangle.MoveOn(...)

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageGenerator.cs
> +            var graphics = Graphics.FromImage(bitmap);
Встречался с IDisposable? Советую почитать про это и подправить. 

Если не найдешь материалы, давай поговорим об этом в тг.

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +    internal class CircularCloudLayouterTests
2. Ага, затупил чет. Нет, разумеется не нужно делать падающих тестов)

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageGenerator.cs
> +        public readonly Size ImageSize;
А если будет многопоточный код, ничего не сломается?)

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouter_Should.cs
> +            action.Should().Throw<ArgumentException>().WithMessage("width and height of rectangle must be more than zero");
Проблема в том, что при изменении сообщения, которое так - то не влияет на логику работы и нужно для информативности в искл. ситуациях, начнут валится тесты и в этом придётся разбираться.

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageGenerator.cs
> +            var maxBottom = int.MinValue + 1;
Зачем добавляем 1?

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageGenerator.cs
> +            var width = 2 * Math.Max(Math.Abs(minLeft), Math.Abs(maxRight)) + 5;
откуда берется 5?

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageGenerator.cs
> +        public Bitmap GenerateBitmap(IReadOnlyList<Rectangle> layout)
Зачем тут readonly ограничение?

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloud/CloudImageGenerator.cs
> +        private IReadOnlyList<Rectangle> GetLayout(IEnumerable<Size> rectanglesSizes)
Тоже непонятно зачем readonly, метод можно написать в одну строку, а мы усложняем :(

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloud/RectangleSizeGenerator.cs
> +        public static IReadOnlyList<Size> GetRandomSizesList(int count, Size minSize, Size maxSize)
IEnumerable

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloud/RectangleSizeGenerator.cs
> +            return result.AsReadOnly();
А если не будет AsReadOnly, что случится?

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ErrorTestImageSaver.cs
> +        public static void SaveBitmap(Bitmap bitmap, out string fullPath)
А нам точно нужно использовать out - параметр?

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +        public bool IsTestResultStateFailureOrError()
Почяму публичный

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +        private IReadOnlyList<Rectangle> GetLayout(IEnumerable<Size> rectanglesSizes)
Опять же, IEnumerable достаточно

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +        private IReadOnlyList<Rectangle> GetLayout(IEnumerable<Size> rectanglesSizes)
И такой метод я уже видел :))

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ErrorTestImageSaver.cs
> +        private const string FileNameDateFormat = "yy-MM-dd hh-mm-ss";
А если я у меня два теста упадут в одну секунду?

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +            if (layout.Count > 0 && IsTestResultStateFailureOrError())
А ситуация, когда прямоугольников нету, почему невалидная? Если у меня тесты упали из-за того, что не раскладываются прямоугольники в принципе?

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +            TestContext.Out.WriteLine("Tag cloud visualization saved to file " + fullPath);
Чисто пожелание: давай интерполяцией?

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +
лишние переносы

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ErrorTestImageSaver.cs
> +        static ErrorTestImageSaver()
Зачем нам статический конструктор?

Раз заиспользовал, придётся отдуваться: чем статический конструктор отличается от обычного?

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ErrorTestImageSaver.cs
> +        private const string FileNameDateFormat = "yy-MM-dd hh-mm-ss";
Формат не самый удачный, непонятно где время, а где дата 
![image](https://user-images.githubusercontent.com/54909098/201739023-2ff88a96-86c7-4865-af22-eec7946d4704.png)

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/ErrorTestImageSaver.cs
> +        private static DirectoryInfo GetTestsLogDirectory()
А сможешь рассказать почему сохраняем в папку net48, а не рядом с проектами, допустим. Сразу видно же будет логи?

2022-11-14 18:42 UTC, HELLoWorlD01100 commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +        public void PutNextRectangle_PutsNonIntersectingRectangles_WhenSeveralRectanglesAdded(int rectanglesCount)
по названиям непонятно чем отличаются тесты

2022-11-14 19:36 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouter_Should.cs
> +            action.Should().Throw<ArgumentException>().WithMessage("width and height of rectangle must be more than zero");
\+

2022-11-14 20:07 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            return new[] { new Vector(deltaX, 0), new Vector(0, deltaY) };
\+
Теперь логику понял)

2022-11-14 20:17 UTC, viksot commented on cs/TagCloud/CircularCloudLayouter.cs
> +            var shiftedLocation = rectangle.Location.MoveOn(direction.X, direction.Y);
\+

2022-11-14 20:21 UTC, viksot commented on cs/TagCloud/CloudImageGenerator.cs
> +        public readonly Size ImageSize;
Это поле ушло после введение автосайзинга изображения по содержимому облака.

В многопоточном коде особых навыков не имеется. Но предположу, что открытое поле может быть изменено в нескольких потоках одновременно. Потоки будут влиять друг на друга.

2022-11-14 21:11 UTC, viksot commented on cs/TagCloud/CloudImageGenerator.cs
> +        public Bitmap GenerateBitmap(IReadOnlyList<Rectangle> layout)
Костыль. При типе аргумента IEnumerable появляется предупреждение о возможном множественном перечислении

![image](https://user-images.githubusercontent.com/106755507/201763627-d43970de-91d6-4da5-8a19-cbaf504a3901.png)

Заменил на IList. Пришлось в нескольких местах заменить выходные значения методов с IEnumerable на IList

2022-11-14 21:25 UTC, viksot commented on cs/TagCloud/CloudImageGenerator.cs
> +        private IReadOnlyList<Rectangle> GetLayout(IEnumerable<Size> rectanglesSizes)
\+

2022-11-14 21:37 UTC, viksot commented on cs/TagCloud/CloudImageGenerator.cs
> +            var maxBottom = int.MinValue + 1;
Дальше идёт получение абсолютной величины maxBottom. Теоретически возможно переполнение, так  как Abs(int.MinValue) > int.MaxValue на 1

![image](https://user-images.githubusercontent.com/106755507/201770278-c9782f97-2d3d-479d-b47b-75776d3703ce.png)

Наверное логичнее сделать так
![image](https://user-images.githubusercontent.com/106755507/201775123-92462ff9-f184-45bb-be61-dd2dd9570357.png)

2022-11-14 22:00 UTC, viksot commented on cs/TagCloud/CloudImageGenerator.cs
> +            var width = 2 * Math.Max(Math.Abs(minLeft), Math.Abs(maxRight)) + 5;
Это окантовка. Если без окантовки, то у крайних прямоугольников одна сторона не попадёт в изображение. Так как отрисовка контура прямоугольника идёт с помощью Pen шириной Pen.Width "наружу" от области, ограниченной прямоугольником. Например, фактическая ширина прямоугольника с учётом границ на изображении будет rectangle.Width + 2*pen.Width

![image](https://user-images.githubusercontent.com/106755507/201777049-e6f277f2-1f65-4aee-944e-d099055daff8.png)

2022-11-14 22:02 UTC, viksot commented on cs/TagCloud/RectangleSizeGenerator.cs
> +        public static IReadOnlyList<Size> GetRandomSizesList(int count, Size minSize, Size maxSize)
Так это метод, который наружу выдаёт коллекцию размеров. Надо же обезопасить коллекцию от изменения, чтобы, например, в неё не добавили размеры, выходящие за ограничения Size minSize, Size maxSize

2022-11-14 22:06 UTC, viksot commented on cs/TagCloud/RectangleSizeGenerator.cs
> +            return result.AsReadOnly();
/+

Судя по всему, ничего

2022-11-14 22:12 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +            if (layout.Count > 0 && IsTestResultStateFailureOrError())
Так если прямоугольники не раскладываются/отсутствуют, то и рисовать нечего тогда. Изображение будет пустое.

 layout.Count > 0  - условие, чтобы не начинать делать изображение для тестов, в которых не проверяется раскладка. Например:
![image](https://user-images.githubusercontent.com/106755507/201779007-a7b0c36d-a267-46dd-8feb-0f7f93884fa4.png)

2022-11-14 22:21 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +        private IReadOnlyList<Rectangle> GetLayout(IEnumerable<Size> rectanglesSizes)
1. \+
2. Вынужденная мера. По идее этот метод нужно сделать публичным в классе CircularCloudLayouter. Но, как я понял, у CircularCloudLayouter условием задан интерфейс, и отходить от него нельзя. 
Либо сделать класс  TagCloud, и в нём хранить раскладку. Но уже обсуждали, что это YAGNI нарушает

2022-11-14 22:22 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +        public bool IsTestResultStateFailureOrError()
\+

2022-11-14 22:24 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +            TestContext.Out.WriteLine("Tag cloud visualization saved to file " + fullPath);
\+

2022-11-14 22:25 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +
\+

2022-11-14 22:38 UTC, viksot commented on cs/TagCloudUnitTests/ErrorTestImageSaver.cs
> +        static ErrorTestImageSaver()
Цель была настроить папку для сохранения логов (в данном случае изображений).  Сейчас подумал, что логичнее это было сделать в тестовом классе.

Статический конструктор:
1. Не имеет аргументов и модификаторов доступа (по умолчанию private)
2. Не может быть перегружен
3. Вызывается только один раз. Перед созданием первого экземпляра или перед первым вызовом какого-либо метода.
4. Вызывается перед любым специальным конструктором

Применяется для задания значений статическим данным, если они не известны на этапе компиляции. Грубо говоря, позволяет настроить класс

2022-11-14 22:43 UTC, viksot commented on cs/TagCloudUnitTests/ErrorTestImageSaver.cs
> +        public static void SaveBitmap(Bitmap bitmap, out string fullPath)
Можно было бы сделать путь к файлу возвращаемым значением метода SaveBitmap. Но это неинтуитивное поведение метода такой функциональности - обычно void. Так ещё из текущего названия метода не следует, что он строку возвращает - надо переименовать на что-то вроде SaveBitmapAndGetFullPathToFile()

2022-11-15 11:12 UTC, viksot commented on cs/TagCloudUnitTests/ErrorTestImageSaver.cs
> +        private const string FileNameDateFormat = "yy-MM-dd hh-mm-ss";
1. Так под каждый тест и саб тест была отдельная папка. Поэтому конфликта имён из совпадающего времени не было бы

![image](https://user-images.githubusercontent.com/106755507/201888665-d73d9967-e786-42cb-a338-57c15ef765b2.png)

Сейчас переделал так, чтобы саб тесты одного тест-метода были в одной папке.
2. \+

2022-11-15 12:57 UTC, viksot commented on cs/TagCloudUnitTests/ErrorTestImageSaver.cs
> +        private static DirectoryInfo GetTestsLogDirectory()
Думал сохранять в текущую директорию тестов.
Переделал.

2022-11-15 19:12 UTC, viksot commented on cs/TagCloudUnitTests/CircularCloudLayouterTests.cs
> +        public void PutNextRectangle_PutsNonIntersectingRectangles_WhenSeveralRectanglesAdded(int rectanglesCount)
\+

2023-11-23 04:54 UTC, closed without merging