Саша Терентьев
kontur-csharper/tdd pull request #182
Opened 2022-11-07 19:26 UTC by sasharumega

Создал алгоритм распределения и парсер тегов
TODO: тесты......., Распределить рисование и генерацию прямоугольников по разным классам, навести красоту

@Folleach пожалуйста, глянь, буду рад любым рекомендациям!

2022-11-08 12:37 UTC, Folleach requested changes
Напишу тут свободный комментарий

Не увидел реализацию интерфейса, предложенного в основной задаче.
```cs
class CircularCloudLayouter
{
  CircularCloudLayouter(Point center)
  Rectangle PutNextRectangle(Size rectangleSize)
}
```
Его стоило бы реализовать, из-за него было бы отчётливее видно разграничение ответственности. А также стало бы понятнее, на что и как писать тесты. И так можно поступить с любой ответственностью в классе TagCloudBuilder, интерфейсы взаимодействия можно придумать **любые**, задача не ограничивается только предложением в ней :)

На счёт тестов, от них я ожидаю увидеть тесты на каждый компонет, который получится выделить. Не нужно тестировать совсем каждое условие, достаточно будет тестов на твои требования.  
Например: 
Требование: облако тегов должно быть похоже на круг + тесты на это дело
Требование: прямоугольники не должны пересекаться + тесты на это дело

А также ожидаю что смогу увидеть результат упавших тестов, чтобы видеть визуально проблему, а не только цифры. Вероятно тебе придётся это сделать не с использованием winform, представь что твои тесты будут выполняться на какой-нибудь машине внутри CI. Тут тебе вероятно не захочется сидеть и следить за результатом, в идеале поставить тесты и уйти пить чай, а после просмотреть все результаты (это 3 задача)

Я бы рекомендовал сконцентрироваться на структуре кода, нежели чем на алгоритме и отрисовке слов (которое ты кажется ещё не успел сделать)

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/Program.cs
> +        private static extern int AllocConsole();
Вероятно ты хотел видеть консоль winform приложения, но таким образом ты сделал сильную зависимость от операционной системы. Да, я понимаю что в целом тагрет текущего проекта только для windows, но **показать консоль можно было проще**, у тебя ведь этот код вполне работоспособный в качестве консоли.  

Причём в текущей реализации если запустить TagCloud из консоли, засаммонится новая консоль. Хотя обычно, вызывая какую-то программу из консоли, я ожидаю что она подхватит консоль из которой вызывается. Как например делают всяческие grep, cat....

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/TagCloud.csproj
> +</Project>
За net7 и проекта для view лайк, но!  
У тебя сейчас и тесты, и библиотека для рисования облаков тега, и view над библиотекой находятся в одном приложении.  

Например тесты не пригодятся на боевой, это будет лишняя зависимость, которая будет увеличивать размер приложения, а в некоторых случаях библиотеки могут негативно сказываться на работе приложения. Что если разработчики из NUnit захотят выставить какие-то настройки, например для thread pool'a на свои? Из-за этого хотелось бы видеть минимум зависимостей в рабочем приложении.  

То же самое я могу сказать про winform, круто что можно потываться в код в каком-то интерфейсе, но что если нам понадобиться рисовать облако тегов для веба? А может быть для win приложения и веба одновременно?

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/Form1.cs
> +            Paint += new PaintEventHandler(Form1_Paint!);
Paint вызывается при малейшей необходимости перерисовать окно, например при выходе окна за границы монитра. У тебя внутри сейчас идёт перерисовка вместе с пересозданием состояния, так как операция генерации нового состояния не моментальная, пользователь видит зависания. Хотелось бы генерировать состояние единожды, а уже потом его перерисовывать сколь угодно раз.  
Но так как это приложение написано для дебага, можно не учитывать это, чтобы не усложнять :)

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/Form1.cs
> +        }
Круто что оставлена ссылка на то, откуда взят код!

Правда он выбивается из общей стилистики, я думаю ничего плохого если ты исправишь пример под свои нужды. Ну и можно посмотреть на новый (из C# 8) [using statement](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/using)

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/TagCloud.csproj.user
> +</Project>
Это авто-генерируемый средой разработки файл, зачем он в репозитории?

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/TagCloudBuilder.cs
> +    public class TagCloudBuilder
Почему класс называется Builder?

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/TagCloudTests.cs
> +}
Эх, хотелось бы видеть...

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/Form1.cs
> +            Bitmap bitamp = tagCloudBuilder.Bitmap;
Думаю можно было сразу передать )  
Тоже похоже на артефакт скопированного кода

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/Form1.cs
> +                tagCloudBuilder.DrawRectangle(new Rectangle(0, 0, w, h));
А точно ли мы ищем позицию для вот такого конкретного _прямоугольника_?  
Может быть конкретный _прямоугольник_ это то, к чему мы стремимся?

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/TagCloudBuilder.cs
> +        }
Сейчас метод TagCloudBuilder.DrawRectangle делает следующее:
- _Находит позицию_ для прямоугольника по _определённому алгоритму_
- Сохраняет текущее положение всех расположенных прямоугольников и _может сказать, есть ли пересечения_
- _Визиализирует прямоугольники_ (твоя тудушка видимо как раз на вынести эту ответственность)

Не слишком ли много он на себя берёт?

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/TagCloudBuilder.cs
> +        }
Например ответственность за вывод визуализированного он уже на себя не стал брать, что хорошо :)
<details>
  <summary>P. S.</summary>
  S из SOLID
</details>

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/TagCloudBuilder.cs
> +        }
Также что если я захочу изменить расстановку облака тегов под свои нужны?
<details>
  <summary>P. S.</summary>
  O из SOLID
</details>

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/Form1.cs
> +                int h = (int)(25 - (i/40) - r.Next(0,2));
Если размер будет сильно маленький, это будет похоже на спираль, а не на облако
![изображение](https://user-images.githubusercontent.com/32067915/200560180-8f8ca8c5-d8f0-4677-b62c-02c4f5ae7ef5.png)

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/DataParser.cs
> +                    FrequencyDict[word]++;
То есть получаем значение, инкрементируем и... не записываем?

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/DataParser.cs
> +                    FrequencyDict[word]++;
Тут ещё можно через TryGetValue дважды не обращаться к словарь с текущим словом

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/DataParser.cs
> +        public Dictionary<string, int> FrequencyDict = new();
Я бы не давал возможность модифицировать частотный словарь всем, кто его получает

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/Form1.cs
> +            this.Height = 768;
Обновление размера окна при отрисовке окна? Выглядит подозрительно

2022-11-08 12:37 UTC, Folleach commented on TagCloudTask/TagCloudBuilder.cs
> +            foundRectangle = new Rectangle(p - rectangle.Size/2, rectangle.Size);
```cs
new Rectangle(p - rectangle.Size/2, rectangle.Size)
```
Почему в параметрах иногда есть пробелы, а иногда нет?

2022-11-12 23:53 UTC, Folleach requested changes

2022-11-12 23:53 UTC, Folleach commented on TagCloudTests/UnitTest1.cs
> +        }
Кажется что тесты только для демонстрации, но в репозитории не нужно оставлять тесты которые не проходят  

Например снова о CI, в нём могут быть цепочки завязанные на успешности/неуспешности тестов, а тесты которые всегда падают по-сути говорят что тесты никогда не пройдут  
Можно было бы их пометить ignored аттрибутом, но а вообще так лучше не делать

2022-11-12 23:53 UTC, Folleach commented on TagCloudTests/UnitTest1.cs
> +        [Test,Timeout(3000)]
Что-то с форматированием снова, у меня rider такое исправляет, если попросить

2022-11-12 23:53 UTC, Folleach commented on TagCloudTests/UnitTest1.cs
> +    }
Тестов можно сделать больше, например сейчас довольно большой простор чтобы написать багов, а тесты говорят что всё ок  
![изображение](https://user-images.githubusercontent.com/32067915/201498321-ea5cbca1-a865-421a-8d1a-75c5212eb1fc.png)

2022-11-12 23:53 UTC, Folleach commented on TagCloudTests/UnitTest1.cs
> +    }
Хотя tdd предполагает что разработка проходит в этапы:
1. Написать тест, что должен сделать код (как правило на маленькую часть, например: "прямоугольники должны стремиться к центру")
2. Написать код, чтобы тест был зелёный
3. Вернуться к 1-ому пункту

При таком подходе тесты, кажется, будут выразительнее
> Ревьюеру должно быть легко по тесту понять проверяемое требование.

Сейчас я вижу что требования:
- рисовать быстро
- рисовать столько, сколько попросили
- не рисовать нулевые площади
- центр только в положительных координатах

2022-11-12 23:53 UTC, Folleach commented on TagCloud2/Program.cs
> +        public static void Main()
Сейчас я получил код с репозитория в котором у меня требуется какой-то непонятный файл `2.txt`  
Стоит держать код в работоспособном состоянии, потому что не всегда файлы и другие внешние ресурсы которые требуются коду — очевидны. Тем не менее и с очевидными тоже не стоит таким пренебрегать

2022-11-12 23:53 UTC, Folleach commented on TagCloud2/SpiralTagCloud.cs
> +        }
Не используется  
Также я бы задумался, а стоит классу ли проксировать метод зависимости?

2022-11-12 23:53 UTC, Folleach commented on TagCloud2/SpiralTagCloud.cs
> +        public readonly ITagCloduBitmapDrawer Drawer;
Опечатка

2022-11-12 23:53 UTC, Folleach commented on TagCloud2/SpiralTagCloudBitmapDrawer.cs
> +        public void DrawTags(Rectangle[] rectangles, Tuple<string, int>[] tags)
Так `DrawTags` или `DrawRectangles`?

2022-11-12 23:53 UTC, Folleach commented on TagCloudTests/UnitTest1.cs
> +        }
Тут вроде бы не `PutNextRectangle` тестируется, а в названии написано что `PutNextRectangle`

Кстати, аттрибут Test в данном случае не нужен, у тебя есть TestCase

2022-11-12 23:53 UTC, Folleach commented on TagCloudTests/UnitTest1.cs
> +    public class Tests
Что-то тут названия класса и файла разъехались, а файл какой-то непонятный `UnitTest1.cs`

2022-11-13 05:18 UTC, sasharumega commented on TagCloudTests/UnitTest1.cs
> +    public class Tests
+

2022-11-13 05:19 UTC, sasharumega commented on TagCloudTests/UnitTest1.cs
> +        }
\+

2022-11-13 05:23 UTC, sasharumega commented on TagCloud2/SpiralTagCloudBitmapDrawer.cs
> +        public void DrawTags(Rectangle[] rectangles, Tuple<string, int>[] tags)
А как назвать, если там только текстовые теги рисуются?) Прям-ки только для координат

2022-11-13 05:24 UTC, sasharumega commented on TagCloud2/SpiralTagCloud.cs
> +        public readonly ITagCloduBitmapDrawer Drawer;
да, действительно, кринжанул

2022-11-13 05:25 UTC, sasharumega commented on TagCloud2/SpiralTagCloud.cs
> +        }
Да, ты прав. Видимо, рудимент. Все работает через интерфейс

2022-11-13 05:25 UTC, sasharumega commented on TagCloud2/Program.cs
> +        public static void Main()
\+

2022-11-13 06:23 UTC, sasharumega commented on TagCloudTests/UnitTest1.cs
> +    }
\+

2022-11-13 06:32 UTC, sasharumega commented on TagCloudTask/Form1.cs
> +            this.Height = 768;
\+

2022-11-13 06:32 UTC, sasharumega commented on TagCloudTask/DataParser.cs
> +        public Dictionary<string, int> FrequencyDict = new();
\+

2022-11-13 12:34 UTC, Folleach commented on TagCloud2/SpiralTagCloudBitmapDrawer.cs
> +        public void DrawTags(Rectangle[] rectangles, Tuple<string, int>[] tags)
А, да, всё правильно  
Сам изменил код и сам же спросил что такое )

2022-11-13 12:58 UTC, Folleach commented on TagCloud2/Program.cs
> +        public static void Main()
Сейчас файл большого значения не имеет, потому что не копируется к бинарникам

2023-11-23 04:54 UTC, closed without merging