Глушаков Максим
kontur-csharper/tdd pull request #190
Opened 2022-11-08 22:21 UTC by madmax46

@coffee_and_problems

2022-11-09 17:37 UTC, coffee-and-problems commented on cs/tdd.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Tests", "Tests", "{80C2AA2B-A45D-47F2-9437-24AC59221E8A}"
что это за проект?

2022-11-09 17:37 UTC, coffee-and-problems commented on cs/TagsCloudVisualizationTests/CircularCloudLayouter_Test.cs
> +        var rectangle = _layouter!.PutNextRectangle(new Size(0, 0));
тут опечатка: параметры width и height наверное должны прокидываться в Size

2022-11-09 17:37 UTC, coffee-and-problems commented on cs/TagsCloudVisualizationTests/CircularCloudLayouter_Test.cs
> +    private CircularCloudLayouter? _layouter;
А зачем явно сделал нуллабельным это поле? Оно же гарантировано просетится  в сетапе, тут можно убрать ? (заодно и ! ниже по коду уберутся)

2022-11-09 17:37 UTC, coffee-and-problems commented on cs/TagsCloudVisualizationTests/CircularCloudLayouter_Test.cs
> +    [TestCase(4, 4)]
Почему тут именно 3 тест-кейса и именно такие? Что они проверяют? Можно ли вместо них написать один (т.е. убрать кейсы и генерировать данные в самом тесте) и просто генерировать 2 случайных числа?

2022-11-09 17:37 UTC, coffee-and-problems commented on cs/TagsCloudVisualization/Interfaces/ITagsCloudVisualization.cs
> +public interface ITagsCloudVisualization
этот файл сейчас ничего полезного не делает (как и его наследник, который просто выкидывает исключение), в коде он нигде не используется. Его логичнее было бы не добавлять в этот коммит - ведь коммит должен быть логическим завершенным кусочком. В этом коммите ты добавил построение прямоугольника на спирали, можно было закоммитить только классы, которые относятся к этому действию. А этот файлик оставить полежать до коммита, когда ты или реализуешь отрисовку облака, или тебе понадобится обратиться к методу этого интерфейса

2022-11-09 17:37 UTC, coffee-and-problems commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        if (rectangleSize.IsEmpty)
А почему тут решил возвращать такой прямоугольник, а не null или не кидать исключение, например?

2022-11-09 17:37 UTC, coffee-and-problems commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            throw new ArgumentException("Zero or negative  spiral step are not allowed");
маааленькая придирочка: лишний пробел закрался

2022-11-09 17:37 UTC, coffee-and-problems commented on cs/TagsCloudVisualizationTests/CircularCloudLayouter_Test.cs
> +    public void PutNextRectangle_TwoRectangles_NotIntersect(int width, int height)
Мне нравится, какие тесты ты выделил, молодец)

2022-11-09 17:37 UTC, coffee-and-problems commented on cs/TagsCloudVisualization/ArithmeticSpiral.cs
> +public class ArithmeticSpiral
Потерялись тесты на этот класс

2022-11-09 20:11 UTC, madmax46 commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        if (rectangleSize.IsEmpty)
мне кажется это немного непредсказуемо кидать исключение, ведь если пользователь этого метода не обернет в дополнительный try catch, может что-то поломаться у него. Думаю возвращаться null - вполне неплохой вариант.

2022-11-09 20:25 UTC, madmax46 commented on cs/tdd.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Tests", "Tests", "{80C2AA2B-A45D-47F2-9437-24AC59221E8A}"
Это так папки выделяются в sln. Проект TagsCloudVisualizationTests содержится в папке Tests

2022-11-09 20:27 UTC, madmax46 commented on cs/TagsCloudVisualizationTests/CircularCloudLayouter_Test.cs
> +    private CircularCloudLayouter? _layouter;
На прошлых занятиях подсмотрел эту штуку в проектах

2022-11-09 20:28 UTC, madmax46 commented on cs/TagsCloudVisualizationTests/CircularCloudLayouter_Test.cs
> +    [TestCase(4, 4)]
Проверяют, что переданный размер и размер полученного прямоугольника одинаковы. В целом, да, можно отказаться от тест кейсов

2022-11-14 12:12 UTC, coffee-and-problems commented
![image](https://user-images.githubusercontent.com/55941390/201656734-cca164ff-4173-49a2-8a2d-f999c96b2ff7.png)

В истории что-то странное происходит, не понятно зачем делать пустой мердж этой ветки, ты же сделал все эти изменения отдельными коммитами. Можно было бы просто удалить эту ветку, раз она оказалась не нужна

2022-11-14 13:19 UTC, coffee-and-problems requested changes

2022-11-14 13:19 UTC, coffee-and-problems commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        if (rectangleSize.IsEmpty)
И все-таки почему именно такой прямоугольник?)  Это же даже не дефолтное значение для класса)

2022-11-14 13:19 UTC, coffee-and-problems commented on cs/TagsCloudVisualization/Interfaces/ITagsCloudVisualization.cs
> +public interface ITagsCloudVisualization
Фишка интерфейса как раз в том, что можно везде заиспользовать именно его, а не конкретный класс, что позволит легко подменять реализации, не меняя контракт. Подробнее можно почитать в [этой статье про инверсию зависимостей](https://metanit.com/sharp/patterns/5.5.php). Сейчас вся суть существования интерфейса не используется в коде:(

2022-11-14 13:19 UTC, coffee-and-problems commented on cs/TagsCloudVisualization/Program.cs
> +new BitmapTagsCloudVisualization().SaveTagsCloud(squareRectLayout, "Images\\SquareRectLayout.bmp");
Тут не обязательно каждый раз создавать новый экземпляр BitmapTagsCloudVisualization - это просто лишний расход памяти будет. Давай вынестем поле `ITagsCloudVisualization tagsCloudVisualization = new BitmapTagsCloudVisualization();` и везде дергать его метод `tagsCloudVisualization.SaveTagsCloud(...)`. Так и избежим ненужных аллокаций и сборки мусора, и заиспользуем интерфейс, получив все плюшки инверсии зависимостей.

2022-11-14 13:19 UTC, coffee-and-problems commented on cs/TagsCloudVisualization/Program.cs
> +var verticalRectLayout = new CircularCloudLayouter(new Point(0, 0), 0.01);
Аналогично можно вынести в переменную, классы же ничем друг от друга не отличаются. Если хочется в коде для читаемости отделить построение облаков с разными видами прямоугольников, то предлагаю использовать `#region ... #endregion`

2022-11-14 13:19 UTC, coffee-and-problems commented on cs/tdd.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Tests", "Tests", "{80C2AA2B-A45D-47F2-9437-24AC59221E8A}"
Обычно тесты кладут рядом с проектом, на который они написаны, не создавая дополнительных папок. Но эти требования могут варьироваться в зависимости от команды

2022-11-14 13:32 UTC, madmax46 commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        if (rectangleSize.IsEmpty)
почему не дефолтное, вполне дефолтное. Потому что возвращение пустого прямоугольника ничего не сломает, и проверка на isEmpty затратит меньше ресурсов, чем catch
![image](https://user-images.githubusercontent.com/32897932/201672368-3cf399d0-3d33-4695-87c4-07cd67281e3e.png)

2022-11-14 13:35 UTC, madmax46 commented on cs/TagsCloudVisualization/Interfaces/ITagsCloudVisualization.cs
> +public interface ITagsCloudVisualization
Согласен, теряется, но теряется на конкретный момент в текущей реализации, если бы мы хотели в будущем сохранять по другому, мы бы просто заменили класс, вызываемый через интерфейс.

2022-11-14 13:53 UTC, coffee-and-problems commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        if (rectangleSize.IsEmpty)
Да, ты прав, Size и Rectangle - структуры, я упустила этот момент. Для них действительно дефолтное значение - это дефолтное значение всех их полей

2022-11-14 13:56 UTC, coffee-and-problems commented on cs/TagsCloudVisualization/Interfaces/ITagsCloudVisualization.cs
> +public interface ITagsCloudVisualization
Так у тебя сейчас нету вызовов через интерфейс, ты напрямую класс вызываешь)

2022-11-14 14:01 UTC, coffee-and-problems commented on cs/TagsCloudVisualization/Interfaces/ITagsCloudVisualization.cs
> +public interface ITagsCloudVisualization
Ну и в промышленной разработке качество кода в том числе определяется его открытостью к расширениям - если я захочу на лету подменять способы сохранения (или, например, использовать разные классы в зависимости от ОС пользователя) мне должно быть легко это сделать. Сейчас же код потребует от меня перейти в него и что-то в нем менять, потом повторно тестировать, что ничего в нем не сломалось. Это хрупкий (и не очень хороший) подход, поэтому в бизнес-коде стараются вообще все зависимости делать через интерфейсы

2022-11-14 14:15 UTC, madmax46 commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        if (rectangleSize.IsEmpty)
конечно с этим можно долго обсуждать как правильнее. Возможно самый правильный результат, это иметь метод PutNextRectangle который будет выкидывать Exception при неправильной логике, возлагая всю ответственность правильных данных на разработчика, и метод TryPutNextRectangle, который будет возвращать bool  и out Rectangle.
Это если прослеживать аналогию с generic коллекциями

2022-11-14 14:18 UTC, madmax46 commented on cs/TagsCloudVisualization/Program.cs
> +var verticalRectLayout = new CircularCloudLayouter(new Point(0, 0), 0.01);
к сожалению в текущей реализации создание CircularCloudLayouter один раз не предусматривается, т.к. не был реализован метод Clear. Иначе все прямоугольники, что были добавлены ранее останутся

2022-11-14 14:40 UTC, coffee-and-problems commented on cs/TagsCloudVisualization/Program.cs
> +var verticalRectLayout = new CircularCloudLayouter(new Point(0, 0), 0.01);
Ок, давай тогда так оставим

2022-11-14 14:41 UTC, coffee-and-problems approved these changes

2023-11-23 04:54 UTC, closed without merging