Звездин Роман
kontur-csharper/tdd pull request #193
Opened 2022-11-09 12:45 UTC by Source34

2022-11-09 18:50 UTC, Danko19 requested changes

2022-11-09 18:50 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            Assert.Throws<ArgumentException>(() => new CircularCloudLayouter(new Point(x, y)));
Можно переписать на FluentAssertions через `Should().Throws()`

2022-11-09 18:50 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core/Helpers/DrawScenario.cs
> +        public DrawScenario(int rectanglesCount, int maxHeight, int minHeight, int maxWidth, int minWidth, string imageName, Size imageSize)
Конструктор кажется лишним, нигде не вызывается. А вообще его можно было через вызов вызов другого

2022-11-09 18:50 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core/Interfaces/IArchimedeanSpiral.cs
> +namespace TagsCloudVisualization.Core.Interfaces
Интерфейсы (этот и остальные) кажутся лишними. Мы их объявляем, реализуем, но в местах использования везде ссылаемся на конкретные реализации

2022-11-09 18:50 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +    public class CircularCloudLayouterTests
Не для всех требований из задания есть тесты

2022-11-09 18:50 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            Assert.Throws<ArgumentException>(() => new CircularCloudLayouter(new Point(x, y)));
Предлагаю использовать **FluentAssertions** во всех проверках, для единообразия

2022-11-09 18:50 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +                    Assert.False(rect.IntersectsWith(rect2));
Этот тест не проходит, падает

2022-11-11 11:14 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            Assert.Throws<ArgumentException>(() => new CircularCloudLayouter(new Point(x, y)));
+

2022-11-11 11:14 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core/Helpers/DrawScenario.cs
> +        public DrawScenario(int rectanglesCount, int maxHeight, int minHeight, int maxWidth, int minWidth, string imageName, Size imageSize)
+

2022-11-11 11:14 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +                    Assert.False(rect.IntersectsWith(rect2));
++

2022-11-11 11:15 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core/Interfaces/IArchimedeanSpiral.cs
> +namespace TagsCloudVisualization.Core.Interfaces
++

2022-11-12 08:47 UTC, Danko19 requested changes

2022-11-12 08:47 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +        private Point _center;
`_center` используется только при создании `CircularCloudLayouter`, кажется можно обойтись локальной переменной

2022-11-12 08:47 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +    public class CircularCloudLayouterTests
Насколько я понял, на каждое требование нужно попробовать написать тест
![image](https://user-images.githubusercontent.com/37505721/201466266-a5418cd0-7803-4c96-a3ad-13332e031641.png)

2022-11-12 08:47 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +        public void Setup()
Такой SetUp кажется не очень нужным, потому что в половине все равно тестов создаётся свой `CircularCloudLayouter`. Предлагаю создавать его в тестах всегда

2022-11-12 08:47 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +        public void PutNextRectangle_RectstIsNotIntersects_ShouldBeTrue(int height, int width, int rectCount)
Небольшая опечаточка в названии 😏

2022-11-12 08:47 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            var rectangles = new List<Rectangle>();
Точно нужно отдельно копить `rectngles`? У нас ведь есть `circularCloud.Rectangles`

2022-11-12 08:47 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            foreach (var rect in rectangles)
Код через 2 foreach-а казался понятнее 😅

2022-11-12 08:52 UTC, Danko19 requested changes

2022-11-12 08:52 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            var circularCloud = new CircularCloudLayouter(new Point(height / 2, width / 2));
Из-за того, что создаём локальный `circularCloud` в случае падения картинка не рисуется :(

2022-11-12 15:05 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +        private Point _center;
++

2022-11-12 15:05 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +        public void Setup()
++

2022-11-12 15:05 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +        public void PutNextRectangle_RectstIsNotIntersects_ShouldBeTrue(int height, int width, int rectCount)
++

2022-11-12 15:05 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            var rectangles = new List<Rectangle>();
++

2022-11-12 15:06 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            foreach (var rect in rectangles)
++ Предложил немного другое решение, но уверен читаемость возрасла

2022-11-12 15:06 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            var circularCloud = new CircularCloudLayouter(new Point(height / 2, width / 2));
++

2022-11-12 21:53 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +    public class CircularCloudLayouterTests
Добавил недостающие тесты

2022-11-13 06:50 UTC, Danko19 requested changes

2022-11-13 06:50 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +               return circularCloudLayouter.Rectangles.Any(p => !p.IntersectsWith(rect) && p != rect);
Проверяем непересечение хотя бы с одним прямоугольником кроме себя, а по идее надо со всеми

2022-11-13 06:50 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +                var currentRadius = GetDistance(circularCloudLayouter.Center, rect.GetCenter());
Кажется более правильным брать не центр прямоугольника, а самый отдалённый от центра угол

2022-11-13 06:50 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            var expectedRadius = Math.Sqrt(area / Math.PI) * 1.2;
Немного не понял эту формулу, нужна пояснительная бригада 😅

2022-11-13 06:50 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +                var currentRadius = GetDistance(circularCloudLayouter.Center, rect.GetCenter());
Как вариант, можно потом, когда все прямоугольники уже нарисованы, взять самую левую, правую, верхнюю, нижнюю точку облака (через Min/Max) и сравнить их расстояние с центром - самое большое расстояние и будет радиусом

2022-11-13 06:50 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            radius.Should().BeLessThan(expectedRadius);
Кажется не совсем корректным проверять форму облака через площади. У круга и, скажем, треугольника тоже могут быть разные площади, но форма у них разная

Появилась такая идея. Чтобы проверить форму облака, что она похожа на круг, можно взять эти же угловые точки (левую, правую, верхнюю, нижнюю) и сравнить их расстояние от центра круга между собой. По идее они должны быть примерно одинаковые с небольшим отклонением

2022-11-13 06:50 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +                toCenterByX.IntersectsWith(circularCloudLayouter.Rectangles)
А вот плотность лучше как раз проверять через площадь. Что сумма площадей прямоугольников занимает какой-то процент от площади круга (чем больше тем лучше)

2022-11-14 14:06 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +               return circularCloudLayouter.Rectangles.Any(p => !p.IntersectsWith(rect) && p != rect);
Тут была ошибка в тесте (не со всеми сравнивалось), и в реализации размещения прямоугольников. Границы прямоугольников находились по оси находились на одной координате, и они пересекались. Сейчас прямоугольники размещаются с минимальным расстоянием между друг другом. Отрефакторен тест и сам метод размещения.

2022-11-14 14:11 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            var expectedRadius = Math.Sqrt(area / Math.PI) * 1.2;
Радиус через площадь считаем, с хитрым коэффициентом :)

2022-11-14 14:11 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            radius.Should().BeLessThan(expectedRadius);
++

2022-11-14 14:11 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +                toCenterByX.IntersectsWith(circularCloudLayouter.Rectangles)
++

2022-11-14 18:14 UTC, Danko19 requested changes

2022-11-14 18:14 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            var avgRadius = (int)((top + bottom + left + right) / (double)4);
Кажется более правильным взять не средний радиус, а максимальный, как считаешь?

2022-11-14 18:14 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            var left = circularCloudLayouter.Rectangles.Max(p => p.Left);
Для каких-то сторон нужно брать `Min`

2022-11-14 18:14 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            var tmpRects = new List<Rectangle>(circularCloudLayouter.Rectangles);
Почему не хочешь просто проверить, что каждый прямоугольник не пересекается ни с одним другим кроме себя? Да, будет n^2 проверок, но для теста оптимальность это не самое главное, главное чтобы проверки были исчерпывающие

2022-11-15 09:20 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            var avgRadius = (int)((top + bottom + left + right) / (double)4);
Cогласен, исправил

2022-11-15 09:21 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            var left = circularCloudLayouter.Rectangles.Max(p => p.Left);
Исправлено

2022-11-15 09:32 UTC, Source34 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            var tmpRects = new List<Rectangle>(circularCloudLayouter.Rectangles);
Оно же по сути так и есть, только вместо if(rect != self && ...) мы удаляем из коллекции текущий rect, и ищем пересечения со всеми остальными. Т.е. мы исключаем проверку на самого себя. В плане покрытия тут вроде норм, по итогу, проверяется каждый rect с каждым. 

Мб производительность будет лучше с if чем с remove() из листа, но это уже немного другая история).

2022-11-15 15:06 UTC, Danko19 commented on cs/TagsCloudVisualization/TagsCloudVisualization.Core.Tests/CircularCloudLayouterTests.cs
> +            var tmpRects = new List<Rectangle>(circularCloudLayouter.Rectangles);
Код реализации "в лоб" с проверкой всех со всеми был бы проще и читался бы лучше, что для немаловажно для тестов. Но это не критично и скорее вкусовщина, докапываться не буду

2023-11-23 04:54 UTC, closed without merging