Ясиновский Саша
kontur-csharper/tdd pull request #195
Opened 2022-11-09 17:59 UTC by Alex2021cyberhuman

Привет, @Leoltron.
Это пулл реквест для предедлайна.

2022-11-11 04:53 UTC, Leoltron requested changes

2022-11-11 04:53 UTC, Leoltron commented on cs/TagCloudVisualization.UnitTests/RectangleAssertionExtensionsTest.cs
> +        a.TouchesWith(b).Should().BeFalse();
Кажется, это все можно обобщить и добавить больше случаев. Прямоугольники могут пересекаться и касаться многми способами

2022-11-11 04:53 UTC, Leoltron commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        return shiftOffset;
Есть способ поэлегантнее вычислить, куда надо двигать прямоугольник

2022-11-11 04:53 UTC, Leoltron commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +    private Rectangle ShiftRectangleCloserToCenterByOne(Rectangle rectangle)
Идея правильная, надо дожать. Представь, что ты тянешь прямоугольник из example1.png к центру. Как бы он двигался?

2022-11-11 04:53 UTC, Leoltron commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        viewBoard = new(Point.Empty, new Size(center) * 2);
В условиях нигде не сказано, что поле ограничено. Более того, когда ты будешь делать следующие части задания, у тебя возникнет проблема того, что слишком большой текст просто не "влезет" в этот Layouter

2022-11-11 04:53 UTC, Leoltron commented on cs/TagCloudVisualization.UnitTests/CircularCloudLayouterTests.cs
> +    }
Throws когда? Или это поведение конструктора по умолчанию?

2022-11-11 04:53 UTC, Leoltron commented on cs/TagCloudVisualization.UnitTests/CircularCloudLayouterTests.cs
> +        action.Should().Throw<InvalidOperationException>();
Название теста говорит о том, что проверяется переполнение поля. Но в самом тесте проверяется две ситуации:

1. Что первый прямоугольник влезет
2. Что второй не влезет

2022-11-11 04:53 UTC, Leoltron commented on cs/TagCloudVisualization.UnitTests/CircularCloudLayouterTests.cs
> +        var rectangleSize = new Size(500, 500);
В этапе Arrange не все перед глазами, мне нужно угадать, что размер раскладчика ограничен 500 (что, отсылая к комменту в самом конструкторе, вообще не очевидно)

2022-11-11 04:53 UTC, Leoltron commented on cs/TagCloudVisualization.UnitTests/CircularCloudLayouterTests.cs
> +public class CircularCloudLayouterTests
Нет тестов для требований:

- Форма итогового облака должна быть близка к кругу с центром в точке center.
- Облако должно быть плотным, чем плотнее, тем лучше.

2022-11-11 04:53 UTC, Leoltron commented on cs/TagsCloudVisualization/PresentationExtensions.cs
> +[SuppressMessage("Interoperability", "CA1416:Проверка совместимости платформы")]
Нацель проект на `net6.0-windows` чтобы никого не смущать использованием `System.Drawing`

2022-11-11 04:53 UTC, Leoltron commented on cs/TagsCloudVisualization/PresentationExtensions.cs
> +            throw new NotImplementedException("implemented only for windows");
См. выше

2022-11-11 04:53 UTC, Leoltron commented on cs/TagsCloudVisualization/PresentationExtensions.cs
> +        return rectangle;
К чему эти расширения, когда можно просто слегка дополнить CircularCloudLayouter и превратить этот класс в общую рисовалку набора прямоугольников?

2022-11-11 05:02 UTC, Alex2021cyberhuman commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +    private Rectangle ShiftRectangleCloserToCenterByOne(Rectangle rectangle)
Я думаю, можно двигать блок до тех пор пока он не соприкасается не с кем, а потом как коснется с другими блоками - пробовать двигать вдоль, по направлению к центру.

2022-11-11 05:02 UTC, Alex2021cyberhuman commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +        viewBoard = new(Point.Empty, new Size(center) * 2);
Понял - переделаю

2022-11-11 05:05 UTC, Alex2021cyberhuman commented on cs/TagCloudVisualization.UnitTests/CircularCloudLayouterTests.cs
> +    }
Constructor_Throws_ThisParameters или
Constructor_ShouldThrows_WhenCallingWithThisParameters или
Constructor_ShouldThrows_WhenCallingWithPointThatConstructedUsingThisParameters?
Как лучше?

2022-11-13 08:13 UTC, Alex2021cyberhuman commented on cs/TagCloudVisualization.UnitTests/CircularCloudLayouterTests.cs
> +public class CircularCloudLayouterTests
PutNextRectangle_SeveralRectangleThatAreLocatedQuiteTightlyInsideCircle_SeveralValidSizes

2022-11-13 18:21 UTC, Leoltron commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
> +            Math.Clamp(center.Y - rectangleCenter.Y, -1, 1));
Math.Sign

2022-11-14 07:34 UTC, Leoltron commented on cs/TagsCloudVisualization/CircularCloudLayouter.cs
>              throw new ArgumentException("center point is invalid", nameof(center));
Теперь эта проверка бесмысленна

2022-11-14 07:34 UTC, Leoltron commented on cs/TagCloudVisualization.UnitTests/CircularCloudLayouterTests.cs
> +    }
Constructor_Throws_WithInvalidParameters

2022-11-14 07:40 UTC, Leoltron approved these changes

2022-11-14 07:40 UTC, closed without merging