Азанов Андрей
kontur-csharper/tdd pull request #225
Opened 2023-12-05 16:39 UTC by Azkraft

@the_homeless_god

2023-12-05 22:15 UTC, the-homeless-god requested changes

2023-12-05 22:15 UTC, the-homeless-god commented on cs/TagsCloudVisualization/TagsCloudTest/UnitTest1.cs
> +        public void DensityTest()
Как считаешь каким образом можно повысить читаемость теста?

Чтобы не вчитываясь в код понять что делает этот тест?

2023-12-05 22:15 UTC, the-homeless-god commented on cs/TagsCloudVisualization/TagsCloudVisualization.sln
> +# Visual Studio Version 17
Как считаешь какую версию IDE стоит использовать и почему?

2023-12-05 22:15 UTC, the-homeless-god commented on cs/TagsCloudVisualization/TagsCloudVisualization/Program.cs
> +TagCloudSaver.Save(tagCloudLayouter.TagCloud, "image.png");
Мог бы аргументировать для чего это? И нужно ли оно?

2023-12-05 22:15 UTC, the-homeless-god commented on cs/TagsCloudVisualization/TagsCloudVisualization/TagCloudSaver.cs
> +            bitmap.Save(fileName);
Что делать если будет IO ошибка?

2023-12-05 22:15 UTC, the-homeless-god commented on cs/TagsCloudVisualization/TagsCloudVisualization/TagCloudSaver.cs
> +            using var bitmap = new Bitmap(1000, 1000);
Есть ли какие-то способы по избавлению от магических чисел?

2023-12-05 22:15 UTC, the-homeless-god commented on cs/TagsCloudVisualization/TagsCloudVisualization/TagCloudSaver.cs
> +        private static Random random = new();
Как считаешь в чём плюсы или минусы короткой записи и полной?

`new ()` vs `new Random()` ?

2023-12-05 22:15 UTC, the-homeless-god commented on cs/TagsCloudVisualization/TagsCloudVisualization/TagCloudSaver.cs
> +            var color = Color.FromKnownColor((KnownColor)(1 + random.Next(175)));
`var` vs объявление типа?

2023-12-05 22:15 UTC, the-homeless-god commented on cs/TagsCloudVisualization/TagsCloudVisualization/TagCloudSaver.cs
> +            for (var i = rectangle.Left; i <= rectangle.Right; i++)
Есть ли риски попасть в бесконечный цикл?

2023-12-05 22:15 UTC, the-homeless-god commented on cs/TagsCloudVisualization/TagsCloudVisualization/TagCloudSaver.cs
> +                bitmap.SetPixel(i, rectangle.Bottom, color);
Есть идеи что делать с дублированием кода?

2023-12-05 22:15 UTC, the-homeless-god commented on cs/TagsCloudVisualization/TagsCloudVisualization/TagCloudSaver.cs
> +                bitmap.SetPixel(rectangle.Right, i, color);
Есть идеи что делать с дублированием кода?

2023-12-05 22:15 UTC, the-homeless-god commented on cs/TagsCloudVisualization/TagsCloudTest/UnitTest1.cs
> +    public class Tests
Как считаешь название файла должно быть таким же как имя класса?

И имя класса Tests не слишком ли обширно?

2023-12-05 22:15 UTC, the-homeless-god commented on cs/TagsCloudVisualization/TagsCloudTest/UnitTest1.cs
> +            circularLayouter = new CircularCloudLayouter(new(500, 500));
Стоит ли тестировать пограничные случаи?

2023-12-09 02:40 UTC, Azkraft commented on cs/TagsCloudVisualization/TagsCloudTest/UnitTest1.cs
> +        public void DensityTest()
Одно из требований — высокая плотность размещения прямоугольников. Может быть так и назвать?

2023-12-09 03:07 UTC, Azkraft commented on cs/TagsCloudVisualization/TagsCloudVisualization.sln
> +# Visual Studio Version 17
Последнюю стабильную версию, как и с большинством другого ПО. У меня нет причин выбирать предыдущие версии. У 2019-ой студии вроде как поддержка в 2024-ом заканчивается, для редакции Community уж наверняка. Не очень перспективно выходит

2023-12-09 03:09 UTC, Azkraft commented on cs/TagsCloudVisualization/TagsCloudVisualization/Program.cs
> +TagCloudSaver.Save(tagCloudLayouter.TagCloud, "image.png");
Не нужно. Использовалось для проверки визуализации

2023-12-09 03:19 UTC, Azkraft commented on cs/TagsCloudVisualization/TagsCloudVisualization/TagCloudSaver.cs
> +            bitmap.Save(fileName);
Ну, неуправляемые ресурсы должны освободиться благодаря using, а проблемы из-за которых произошла ошибка, наверное, должна решать вызывающая сторона

2023-12-09 03:22 UTC, Azkraft commented on cs/TagsCloudVisualization/TagsCloudVisualization/TagCloudSaver.cs
> +            using var bitmap = new Bitmap(1000, 1000);
Нужно вычислить габариты облака и сделать расчёт параметров изображения

2023-12-09 03:31 UTC, Azkraft commented on cs/TagsCloudVisualization/TagsCloudVisualization/TagCloudSaver.cs
> +            for (var i = rectangle.Left; i <= rectangle.Right; i++)
Такое может случиться, если rectangle.Right == int.MaxValue

2023-12-09 03:39 UTC, Azkraft commented on cs/TagsCloudVisualization/TagsCloudVisualization/TagCloudSaver.cs
> +        private static Random random = new();
Помогает избежать дублирование типа при инициализации переменных или полей. О недостатках не знаю

2023-12-09 03:45 UTC, Azkraft commented on cs/TagsCloudVisualization/TagsCloudVisualization/TagCloudSaver.cs
> +            var color = Color.FromKnownColor((KnownColor)(1 + random.Next(175)));
Помогает избежать дублирования типа при инициализации переменных с помощью оператора new и при инициализации литералами. С другой стороны не всегда очевидно какой тип имеет переменная, как в данном случае

2023-12-09 03:51 UTC, Azkraft commented on cs/TagsCloudVisualization/TagsCloudTest/UnitTest1.cs
> +    public class Tests
Имя типа должно совпадать с именем класса. Я хотел все тесты разместить в классе Tests. Есть ли смысл его в таком случае переименовывать?

2023-12-09 03:53 UTC, Azkraft commented on cs/TagsCloudVisualization/TagsCloudTest/UnitTest1.cs
> +            circularLayouter = new CircularCloudLayouter(new(500, 500));
Да. Можно было бы отловить зацикливание

2023-12-09 04:44 UTC, Azkraft commented on cs/TagsCloudVisualization/TagsCloudVisualization/TagCloudSaver.cs
> +                bitmap.SetPixel(i, rectangle.Bottom, color);
Да. Можно воспользоваться встроенным методом Graphics.DrawRectangles и не мучиться. Или можно было вложить один цикл в другой, добавить условий и оставить один SetPixel

2025-03-15 20:46 UTC, closed without merging